final List<Map<String, String>> main_categories = [
  {"title": "صباحو تحدي", "image": "assets/main/saba7o.png", "path": "/saba7o"},
  {"title": "تحدي ال30", "image": "assets/main/30 Challenge.png", "path": "/challenge"},
  {"title": "أقوي تحدي", "image": "assets/main/Aqua Ta7ady.png", "path": "/aqua"},
  {"title": "دور ال16", "image": "assets/main/round.png", "path": "/round"},
];



final List<Map<String, String>> saba7o_categories = [
  {"title": "اهبد صح", "image": "assets/main/saba7o.png", "path": "/ehbed","rules":"سؤال وكل فريق معاه 30 ثانية علشان يجاوب واللي اجابته اقرب بياخد نقطة ولو حد جاب اجابة صح بياخد نقطتين"},
  {"title": "اكدب صح", "image": "assets/main/saba7o.png", "path": "/ekdeb","rules":"s"},
  {"title": "روندو", "image": "assets/main/saba7o.png", "path": "/rondo","rules":"s"},
  {"title": "مين في الصورة", "image": "assets/main/saba7o.png", "path": "/men_fe_elsora","rules":"sss"},
  {"title": "الهمس ", "image": "assets/main/saba7o.png", "path": "/whisper","rules":"sssss"},
  {"title": "5*10", "image": "assets/main/saba7o.png", "path": "/seconds","rules":"ssssss"},
  {"title": "من اللاعب", "image": "assets/main/saba7o.png", "path": "/guess_the_player","rules":"sssss"},
  {"title": "باسورد", "image": "assets/main/saba7o.png", "path": "/password","rules":"sssss"},
  {"title": "ريسك", "image": "assets/main/saba7o.png", "path": "/risk","rules":"sssss"},
  {"title": "بنك", "image": "assets/main/saba7o.png", "path": "/bank","rules":"sssss"},
  {"title": "لبس صاحبك", "image": "assets/main/saba7o.png", "path": "/labes_sa7bak","rules":"sssssssss"},
  {"title": "مزاد", "image": "assets/main/saba7o.png", "path": "/mazad","rules":"sssssss"},
  {"title": "الرسم", "image": "assets/main/saba7o.png", "path": "/draw","rules":"sssssss"},
  {"title": "التمثيل", "image": "assets/main/saba7o.png", "path": "/acting","rules":"sssss"},
];


final List<Map<String, dynamic>> Ehbed_data = [
  {"question": "امتي كانت اول مرة الاهلي ياخد الدوري من غير هزيمة؟", "answer": 1976},
  {"question": "كام لاعب جاب 100+ جون في البريميرليج؟", "answer": 34},
  {"question": "هازارد سجل كام جون مع المنتخب؟", "answer": 33},
  {"question": "دينس بيركامب عمل كام اسيست في البريميرليج؟", "answer": 94},
  {"question": "بيتر تشيك عمل كام سيف في الدوري الانجليزي؟", "answer": 1005},
  {"question": "لامبارد جاب كام بلن مع تشيلسي في الدوري الانجليزي؟", "answer": 32},
  {"question": "ماكسويل اخد كام بطولة؟", "answer": 37},
  {"question": "مجموع الفلوس في انتقالات دي ماريا؟", "answer": 179},
  {"question": "هاندانوفيتش لعب كام ماتش مع انتر ميلان؟", "answer": 455},
  {"question": "البرازيل لعبت كام ماتش في كاس العالم؟", "answer": 114},
  {"question": "اكبر انتصار في كاس العالم كان للمجر علي الهندوراس 10-1 كان سنة كام؟", "answer": 1982},
  {"question": "اكتر عدد اهداف سجله منتخب في بطولة واحدة من كاس العالم؟", "answer": 27},
  {"question": "اكتر saves في ماتش واحد كانت لتيم هاورد كانوا كام save ؟", "answer": 16},
  {"question": "ايه اكبر عدد مرات متتالية ريال مدريد اخد فيها الدوري ؟", "answer": 5},
  {"question": "بوردو أخدوا كام دوري ؟", "answer": 6},
  {"question": "ديبورتيفولاكرونيا اكتر فريق اتعادل في موسم في الدوري الاسباني سنة 2016 كانوا كام؟", "answer": 18},
  {"question": "اطول سلسلة لا هزيمة في الدوري الاسباني كام ماتش؟", "answer": 43},
  {"question": "ميسي سجل قصاد كام فريق في الدوري الاسباني؟", "answer": 38},
  {"question": "رونالدو وصل ل300 هدف في الدوري الاسباني في كام ماتش؟", "answer": 286},
  {"question": "اكتر عدد مباريات متتالي لميسي يسجل فيه هدف علي الاقل؟", "answer": 21},
  {"question": "ميسي جاب كام هاتريك في الدوري الاسباني؟", "answer": 36},
  {"question": "دي خيا أخد كام بطولة مع اليونايتد (من غير الكومينتي) ؟", "answer": 5},
  {"question": "ميسي سجل اكتر من 30 جون في الدوري كام مرة؟", "answer": 8},
  {"question": "ديجو الفيس حارس اشبيلية اكتر حارس صد بلنتيات في موسم واحد في الدوري كانوا كام؟", "answer": 6},
  {"question": "راموس اخد كام كارت احمر؟", "answer": 20},
  {"question": "سواريز جاب كام جون في الدوري الاسباني؟", "answer": 179},
  {"question": "كام لاعب سجل اكتر من 35 جون في الدوري الاسباني في موسم واحد؟", "answer": 6},
  {"question": "توني كروس لعب كام ماتش في كأس العالم للاندية؟", "answer": 11},
  {"question": "حسام حسن اخد كام دوري؟", "answer": 15},
  {"question": "بوشكاش جاب كام جون ؟", "answer": 806},
  {"question": "احمد حسن لعب كام ماتش مع المنتخب؟", "answer": 184},
  {"question": "كاسياس عنده كام كلين شيت دولي؟", "answer": 102},
];


final List<Map<String, dynamic>> Ekdeb_data = [
  {"question": "امتي كانت اول مرة الاهلي ياخد الدوري من غير هزيمة؟", "answer": 1976},
  {"question": "كام لاعب جاب 100+ جون في البريميرليج؟", "answer": 34},
  {"question": "هازارد سجل كام جون مع المنتخب؟", "answer": 33},
  {"question": "دينس بيركامب عمل كام اسيست في البريميرليج؟", "answer": 94},
  {"question": "بيتر تشيك عمل كام سيف في الدوري الانجليزي؟", "answer": 1005},
  {"question": "لامبارد جاب كام بلن مع تشيلسي في الدوري الانجليزي؟", "answer": 32},
  {"question": "ماكسويل اخد كام بطولة؟", "answer": 37},
  {"question": "مجموع الفلوس في انتقالات دي ماريا؟", "answer": 179},
  {"question": "هاندانوفيتش لعب كام ماتش مع انتر ميلان؟", "answer": 455},
  {"question": "البرازيل لعبت كام ماتش في كاس العالم؟", "answer": 114},
  {"question": "اكبر انتصار في كاس العالم كان للمجر علي الهندوراس 10-1 كان سنة كام؟", "answer": 1982},
  {"question": "اكتر عدد اهداف سجله منتخب في بطولة واحدة من كاس العالم؟", "answer": 27},
  {"question": "اكتر saves في ماتش واحد كانت لتيم هاورد كانوا كام save ؟", "answer": 16},
  {"question": "ايه اكبر عدد مرات متتالية ريال مدريد اخد فيها الدوري ؟", "answer": 5},
  {"question": "بوردو أخدوا كام دوري ؟", "answer": 6},
  {"question": "ديبورتيفولاكرونيا اكتر فريق اتعادل في موسم في الدوري الاسباني سنة 2016 كانوا كام؟", "answer": 18},
  {"question": "اطول سلسلة لا هزيمة في الدوري الاسباني كام ماتش؟", "answer": 43},
  {"question": "ميسي سجل قصاد كام فريق في الدوري الاسباني؟", "answer": 38},
  {"question": "رونالدو وصل ل300 هدف في الدوري الاسباني في كام ماتش؟", "answer": 286},
  {"question": "اكتر عدد مباريات متتالي لميسي يسجل فيه هدف علي الاقل؟", "answer": 21},
  {"question": "ميسي جاب كام هاتريك في الدوري الاسباني؟", "answer": 36},
  {"question": "دي خيا أخد كام بطولة مع اليونايتد (من غير الكومينتي) ؟", "answer": 5},
  {"question": "ميسي سجل اكتر من 30 جون في الدوري كام مرة؟", "answer": 8},
  {"question": "ديجو الفيس حارس اشبيلية اكتر حارس صد بلنتيات في موسم واحد في الدوري كانوا كام؟", "answer": 6},
  {"question": "راموس اخد كام كارت احمر؟", "answer": 20},
  {"question": "سواريز جاب كام جون في الدوري الاسباني؟", "answer": 179},
  {"question": "كام لاعب سجل اكتر من 35 جون في الدوري الاسباني في موسم واحد؟", "answer": 6},
  {"question": "توني كروس لعب كام ماتش في كأس العالم للاندية؟", "answer": 11},
  {"question": "حسام حسن اخد كام دوري؟", "answer": 15},
  {"question": "بوشكاش جاب كام جون ؟", "answer": 806},
  {"question": "احمد حسن لعب كام ماتش مع المنتخب؟", "answer": 184},
  {"question": "كاسياس عنده كام كلين شيت دولي؟", "answer": 102},
];

final List<Map<String, String>> Rondo_data = [
  {"name": "Juventus", "photo": ""},
  {"name": "Gareth Bale", "photo": ""},
  {"name": "Manchester United", "photo": ""},
  {"name": "Erling Haaland", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
  {"name": "Barcelona", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Paul Pogba", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Harry Kane", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sergio Agüero", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Cody Gakpo", "photo": ""},
  {"name": "N'Golo Kanté", "photo": ""},
  {"name": "Toni Kroos", "photo": ""},
  {"name": "Manuel Neuer", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Chelsea", "photo": ""},
  {"name": "Marco Reus", "photo": ""},
  {"name": "Edouard Mendy", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Christian Pulisic", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "Thomas Müller", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Man City", "photo": ""},
  {"name": "Virgil van Dijk", "photo": ""},
  {"name": "Inter Milan", "photo": ""},
  {"name": "Mohamed Salah", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "Lacazette", "photo": ""},
  {"name": "Gakpo", "photo": ""},
  {"name": "Arsenal", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Muller", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Man United", "photo": ""},
  {"name": "Yannick Carrasco", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Jude Bellingham", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
];
final List<Map<String, String>> Draw_data = [
  {"name": "Juventus", "photo": ""},
  {"name": "Manchester United", "photo": ""},
  {"name": "Barcelona", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "Chelsea", "photo": ""},
  {"name": "Inter Milan", "photo": ""},
  {"name": "Zamalek", "photo": ""},
  {"name": "Arsenal", "photo": ""},
];

final List<Map<String, String>> Password_data = [
  {"name": "Juventus", "photo": ""},
  {"name": "Gareth Bale", "photo": ""},
  {"name": "Manchester United", "photo": ""},
  {"name": "Erling Haaland", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
  {"name": "Barcelona", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Paul Pogba", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Harry Kane", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sergio Agüero", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Cody Gakpo", "photo": ""},
  {"name": "N'Golo Kanté", "photo": ""},
  {"name": "Toni Kroos", "photo": ""},
  {"name": "Manuel Neuer", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Chelsea", "photo": ""},
  {"name": "Marco Reus", "photo": ""},
  {"name": "Edouard Mendy", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Christian Pulisic", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "Thomas Müller", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Man City", "photo": ""},
  {"name": "Virgil van Dijk", "photo": ""},
  {"name": "Inter Milan", "photo": ""},
  {"name": "Mohamed Salah", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "Lacazette", "photo": ""},
  {"name": "Gakpo", "photo": ""},
  {"name": "Arsenal", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Muller", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Man United", "photo": ""},
  {"name": "Yannick Carrasco", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Jude Bellingham", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
];

final List<Map<String, String>> Whisper_data = [
  {"name": "Juventus", "photo": ""},
  {"name": "Gareth Bale", "photo": ""},
  {"name": "Manchester United", "photo": ""},
  {"name": "Erling Haaland", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
  {"name": "Barcelona", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Paul Pogba", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Harry Kane", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sergio Agüero", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Cody Gakpo", "photo": ""},
  {"name": "N'Golo Kanté", "photo": ""},
  {"name": "Toni Kroos", "photo": ""},
  {"name": "Manuel Neuer", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Chelsea", "photo": ""},
  {"name": "Marco Reus", "photo": ""},
  {"name": "Edouard Mendy", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Christian Pulisic", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "Thomas Müller", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Man City", "photo": ""},
  {"name": "Virgil van Dijk", "photo": ""},
  {"name": "Inter Milan", "photo": ""},
  {"name": "Mohamed Salah", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "Lacazette", "photo": ""},
  {"name": "Gakpo", "photo": ""},
  {"name": "Arsenal", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Muller", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Man United", "photo": ""},
  {"name": "Yannick Carrasco", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Jude Bellingham", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
];


final List<Map<String, String>> Acting_data = [
  {"name": "Juventus", "photo": ""},
  {"name": "Gareth Bale", "photo": ""},
  {"name": "Manchester United", "photo": ""},
  {"name": "Erling Haaland", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
  {"name": "Barcelona", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Paul Pogba", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Harry Kane", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sergio Agüero", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Cody Gakpo", "photo": ""},
  {"name": "N'Golo Kanté", "photo": ""},
  {"name": "Toni Kroos", "photo": ""},
  {"name": "Manuel Neuer", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Chelsea", "photo": ""},
  {"name": "Marco Reus", "photo": ""},
  {"name": "Edouard Mendy", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Christian Pulisic", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "Thomas Müller", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Man City", "photo": ""},
  {"name": "Virgil van Dijk", "photo": ""},
  {"name": "Inter Milan", "photo": ""},
  {"name": "Mohamed Salah", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "Lacazette", "photo": ""},
  {"name": "Gakpo", "photo": ""},
  {"name": "Arsenal", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Muller", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Man United", "photo": ""},
  {"name": "Yannick Carrasco", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Jude Bellingham", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
];


final List<Map<String, String>> Seconds_data = [
  {"question": "اذكر 5 ملاعب في اسبانيا", },
  {"question": "اذكر 5 لاعبين مصريين شاركوا في كاس العالم", },
  {"question": "اذكر 5 فرق افريقية غير عربية", },
  {"question": "اذكر 5 لاعبين لعبوا ل برشلونة و مانشتسر سيتي", },
  {"question": "اذكر5  فرق الطقم الاساسي مخطط", },
  {"question": "اذكر 5 اسامي ملاعب في انجلترا", },
  {"question": "اذكر 5 اسماء دول كسبت كاس اسيا", },
  {"question": "اذكر 5 فرق كسبت دوري الابطال وليست من الدوريات الخمسة الكبري", },
  {"question": "اذكر 5 لاعبين انجليز لعبوا بره انجلترا", },
  {"question": "اذكر 5 لاعبين من كوريا الجنوبية", },
  {"question": "اذكر 5 دول خسرت من الارجنتين في كاس العالم 2022", },
  {"question": "اذكر 5 لاعبين حصلوا علي دوري الابطال مع فرقتين مختلفتين", },
  {"question": "اذكر 5 لاعبين لعبوا ل3 فرق او اكتر في نفس الدوري", },
  {"question": "اذكر 5 لاعبين انتقلوا من الدوري الانجليزي ل ريال مدريد", },
  {"question": "اذكر 5 لاعبين انتقلوا من الدوري الانجليزي ل برشلونة", },
  {"question": "اذكر 5 فرق دربهم مورينيو", },
  {"question": "اذكر 5 لاعبين لعبوا كورة و ابنهم لعب كورة", },


];
final List<Map<String, String>> Mazad_data = [
  {"question": "اذكر 5 ملاعب في اسبانيا", },
  {"question": "اذكر 5 لاعبين مصريين شاركوا في كاس العالم", },
  {"question": "اذكر 5 فرق افريقية غير عربية", },
  {"question": "اذكر 5 لاعبين لعبوا ل برشلونة و مانشتسر سيتي", },
  {"question": "اذكر5  فرق الطقم الاساسي مخطط", },
  {"question": "اذكر 5 اسامي ملاعب في انجلترا", },
  {"question": "اذكر 5 اسماء دول كسبت كاس اسيا", },
  {"question": "اذكر 5 فرق كسبت دوري الابطال وليست من الدوريات الخمسة الكبري", },
  {"question": "اذكر 5 لاعبين انجليز لعبوا بره انجلترا", },
  {"question": "اذكر 5 لاعبين من كوريا الجنوبية", },
  {"question": "اذكر 5 دول خسرت من الارجنتين في كاس العالم 2022", },
  {"question": "اذكر 5 لاعبين حصلوا علي دوري الابطال مع فرقتين مختلفتين", },
  {"question": "اذكر 5 لاعبين لعبوا ل3 فرق او اكتر في نفس الدوري", },
  {"question": "اذكر 5 لاعبين انتقلوا من الدوري الانجليزي ل ريال مدريد", },
  {"question": "اذكر 5 لاعبين انتقلوا من الدوري الانجليزي ل برشلونة", },
  {"question": "اذكر 5 فرق دربهم مورينيو", },
  {"question": "اذكر 5 لاعبين لعبوا كورة و ابنهم لعب كورة", },


];


final List<Map<String, String>> Men_fe_elsora_data = [
{"title": "Spurs 2016 vs Atletico Madrid",
"image": "assets/saba7o/men_fe_elsora/spurs2016.jpg",
"player1":"Vorm",
"player2":"Trippier",
"player3":"Walkes",
"player4":"Carter-Vickers",
"player5":"Yedlin",
"player6":"Wanyama",
"player7":"Winks",
"player8":"Lamela",
"player9":"Eriksen",
"player10":"Onomah",
"player11":"Janssen",
},
{
"title": "Atletico 2019 vs Bayer 04 Leverkusen",
"image": "assets/saba7o/men_fe_elsora/atletico2019.jpg",
"player1":"Jan Oblak",
"player2":"Josema Gimenez",
"player3":"Felipe",
"player4":"Thomas Partey",
"player5":"Hector Herrera",
"player6":"Renan Lodi",
"player7":"Angel Correa",
"player8":"Kieran Trippier",
"player9":"Koke",
"player10":"Saul Niguez",
"player11":"Diego Costa",
},
{
"title": "Serbia 2018 vs Brazil",
"image": "assets/saba7o/men_fe_elsora/serbia2018.jpg",
"player1":"V Stojkovic",
"player2":"A Rukavina",
"player3":"N Milenkovic",
"player4":"M Veljkovic",
"player5":"A Kolarov",
"player6":"S Milinkovic-Savic",
"player7":"N Matic",
"player8":"D Tadic",
"player9":"A Ljajic",
"player10":"F Kostic",
"player11":"A Mitrovic",
},
{
"title": "Denmark 2023 vs slovenia",
"image": "assets/saba7o/men_fe_elsora/denmark2023.jpg",
"player1":"Kasper Schmeichel",
"player2":"Simon Kjaer",
"player3":"Mathias Jorgensen",
"player4":"Andreas Christensen",
"player5":"Christian Eriksen",
"player6":"Pierre-Emile Højbjerg",
"player7":"Jens Stryger Larsen",
"player8":"Alexander Bah",
"player9":"Rasmus Højlund",
"player10":"Jonas Wind",
"player11":"Andreas Skov Olsen",
},
{
"title": "Brazil 2002 ",
"image": "assets/saba7o/men_fe_elsora/brazil2002.jpg",
"player1":"Lúcio",
"player2":"Edmílson",
"player3":"Gilberto Silva",
"player4":"Roque Júnior",
"player5":"Ronaldinho",
"player6":"Ronaldo",
"player7":"Marcos",
"player8":"Cafu",
"player9":"Juninho",
"player10":"Roberto Carlos",
"player11":"Rivaldo",
},
{
"title": "Real Madrid 2002 vs Bayer 04 Leverkusen",
"image": "assets/saba7o/men_fe_elsora/realMadrid2002.png",
"player1":"César",
"player2":"Fernando Hierro",
"player3":"Helguera",
"player4":"Santiago Solari",
"player5":"Luís Figo",
"player6":"Zinedine Zidane",
"player7":"Fernando Morientes",
"player8":"Claude Makélélé",
"player9":"Michel Salgado",
"player10":"Raúl",
"player11":"Roberto Carlos",
},
];

final List<Map<String, String>> guessThePlayer_data = [
  {
    "name": "Arthur Melo",
    "Clue 1": "بدأت مسيرتي في نادي غريميو البرازيلي وكسبت معهم الكوبا ليبراتادوريس.",
    "Clue 2": "لعبت لثلاثة من الدوريات الخمسة الكبرى وهم الإنجليزي والإيطالي والإسباني.",
    "Clue 3": "لعبت مع بيلوتي وراكيتيتش وبوفون وكوتينيو ولويس سواريز وتياجو الكانتارا ودوجلاس كوستا ورابيو وميسي.",
    "Clue 4": "فزت بدوريين وكأسين وسوبرين، وخسرت نهائي بطولة قارية مع نادي من الأندية التي لعبت لها في أوروبا.",
    "Clue 5": "فزت بالكوبا أمريكا 2019 مع البرازيل."
  },
  {
    "name": "Hernan Crespo",
    "Clue 1": "لعبت في سبعة فرق طوال مسيرتي، منهم خمسة في الدوري الإيطالي.",
    "Clue 2": "حصلت على جائزة رجل المباراة في نهائي كأس الاتحاد الأوروبي سنة 1999.",
    "Clue 3": "حققت هداف الدوري الإيطالي موسم 2000 وحصلت على الدوري الإيطالي مرتين والدوري الإنجليزي مرة.",
    "Clue 4": "حققت الكأس والسوبر الإيطالي وكأس الاتحاد الأوروبي مع فريق غير موجود بدوري الأبطال حالياً.",
    "Clue 5": "كنت أول لاعب أرجنتيني يسجل ثنائية في نهائي دوري أبطال أوروبا، وأنا مدرب العين الإماراتي الحالي وفزت معهم بدوري أبطال آسيا."
  },
  {
    "name": "Rafael van der Vaart",
    "Clue 1": "لعبت في ثلاثة من الدوريات الخمسة الكبرى وهم الإنجليزي والألماني والإسباني.",
    "Clue 2": "لعبت مع فينسنت كومباني، تشوبوموتينج، ويسلي شنايدر، روبنهو، لوكا مودريتش، فان نيستلروي، وكايل والكر.",
    "Clue 3": "بدأت مسيرتي الاحترافية في نادي أياكس وحصلت معهم على كل الألقاب المحلية.",
    "Clue 4": "حصلت على جائزة موهبة السنة في أياكس موسم 2001 ثم حصلت على جائزة لاعب السنة في موسم 2002.",
    "Clue 5": "فزت بالسوبر الإسباني 2008 وكأس الـFA مع توتنهام 2008، وحصلت على جائزة الجولدن بوي سنة 2003، وأنهيت مسيرتي في فريق دنماركي ثم عملت كمساعد مدرب في الفريق لمدة سنتين."
  },
  {
    "name": "Juan Cuadrado",
    "Clue 1": "لعبت في سبعة فرق مختلفة وسجلت معهم 45 هدفاً.",
    "Clue 2": "بدأت اللعب مع المنتخب الوطني من 2010 ولعبت 115 مباراة سجلت خلالها 11 هدفاً.",
    "Clue 3": "في بداياتي كنت أفضل اللعب كمهاجم، وحالياً أستطيع اللعب في مركزين هما الجناح الأيمن والظهير الأيمن.",
    "Clue 4": "انتقلت إلى فريق جديد هذا الموسم، ولكن جماهير النادي غاضبة من الصفقة بسبب الحادثة التي حدثت بيني وبين حارس مرماهم في مباراة سابقة، وعلي إثر المشكلة تلك حصلت على إيقاف 3 مباريات.",
    "Clue 5": "قيل عني في وجود كريستيانو رونالدو معي في الفريق أنني سانتا كلوزة، أقوم بتوزيع الهدايا عليه وعلى غيره، ولهذا سموني ملك الأسيست. كما كنت على غلاف لعبة FIFA 16 نسخة أمريكا اللاتينية بجانب ميسي."
  },
  {
    "name": "Makroof Youssef",
    "Clue 1": "لعبت في أربعة فرق في الدوري المصري.",
    "Clue 2": "لعبت 100 مباراة مع نادي قمة في مصر في مختلف البطولات.",
    "Clue 3": "على الرغم من أنني لعبت لأربعة فرق في الدوري المصري، إلا أنني سجلت فقط 14 هدفاً في الدوري.",
    "Clue 4": "بدأت مسيرتي في الدوري النيجيري لأني وُلدت في نيجيريا، لكني أملك جنسية أفريقية أخرى ولعبت مع منتخب هذه الجنسية مباراة ودية وحيدة.",
    "Clue 5": "سجلت هدفاً مهماً لنادي الزمالك في مباريات ضد الإسماعيلي وأورلاندو بيراتس."
  }, {
    "name": "Franck Ribéry",
    "Clue 1": "لعب في أربع دوريات أوروبية ولعب نسختين كأس عالم.",
    "Clue 2": "فاز بـ 25 لقبًا في مسيرته على مستوى الأندية، ووصل إلى نهائي دوري الأبطال ثلاث مرات واستطاع الفوز بلقب واحد فقط.",
    "Clue 3": "لعب مع كل من (كلوزه، هنري، جيمس رودريغيز، مامادو نيانج، مارتن كاسيريس، برنس بواتينج، جيروم بواتينج، فريدريكو كييزا، لوكا توني، دييجو بيروتي، كاليخون، لوسيو).",
    "Clue 4": "لعب أكثر من 600 مباراة طوال مسيرته وسجل أكثر من 100 هدف وقام بأكثر من 200 أسيست.",
    "Clue 5": "فاز وترشح للعديد من الألقاب الفردية العالمية، وكان وصيف كأس العالم 2006."
  },
  {
    "name": "Javier Mascherano",
    "Clue 1": "لعب في دوريين فقط على المستوى الأوروبي وشارك في أربع نسخ كأس عالم.",
    "Clue 2": "فاز بـ 19 لقبًا في مسيرته على مستوى الأندية، ووصل إلى نهائي دوري الأبطال ثلاث مرات وفاز بلقبين فقط وكان وصيفًا مرة.",
    "Clue 3": "لعب مع (نيمار، شيرينجهام، أربيلوا، ريكيلمي، بيكيه، أيوب الكعبي، سافيولا، فيرناندو توريس، فابريجاس، أليكس سونج، أليكسيس سانشيز، روبيرتو أيالا).",
    "Clue 4": "لعب أكثر من 500 مباراة طوال مسيرته ولعب لجميع الفئات العمرية لمنتخب بلاده.",
    "Clue 5": "كان وصيف كأس العالم ووصيف كوبا أمريكا أربع مرات، ولم يفز ببطولة مع المنتخب الأول. يعمل الآن كمدرب وفاز ببطولة كمدرب."
  },
  {
    "name": "Mikel Arteta",
    "Clue 1": "فاز بالدوري البرتغالي وكأس البرتغال واثنين كأس الدوري البرتغالي وكأس الملك الإسباني.",
    "Clue 2": "لعب مع منتخب بلاده في ثلاث نهائيات قارية، وكل نهائي كان مع فئة عمرية مختلفة، وكسب اثنين منهم.",
    "Clue 3": "بدأ مسيرته الاحترافية في 2010 وتم استدعاؤه للمنتخب الأول لأول مرة في 2014.",
    "Clue 4": "أخر بطولة كسبها كانت في موسم 2018/2019.",
    "Clue 5": "خسر نهائيين متتاليين في الدوري الأوروبي. كان هداف كأس الملك عندما فاز بها، وأخذ لاعب الشهر في الليجا مرة واحدة فقط."
  },
  {
    "name": "Javier Pastore",
    "Clue 1": "فاز بدوري واحد، سوبر واحد، يوروبا واحد، كأس عالم الأندية واحد، وسوبر أوروبي واحد.",
    "Clue 2": "لعب لكل الفئات العمرية لمنتخب بلاده.",
    "Clue 3": "وصل إلى ثلاث نهائيات قارية مع منتخب بلاده في ثلاث فئات عمرية مختلفة وكسب واحد فقط.",
    "Clue 4": "بدأت مسيرتي الاحترافية في 2012 وتم استدعائي للمنتخب الأول لأول مرة في 2016 وسجلت ثلاثة أهداف في 19 مباراة.",
    "Clue 5": "في منتصف مسيرتي لعبت كقلب دفاع في فريق لم يكن مركزي. أكبر إنجازاتي في دوري الأبطال هو كوني وصيف دوري أبطال أوروبا."
  },
  {
    "name": "Saúl Ñíguez",
    "Clue 1": "سجلت هدفًا في فريق في نهائي بطولة، وبعدها بسنتين انتقلت إلى هذا الفريق.",
    "Clue 2": "فزت بجائزة أفضل لاعب محترف في الدوري الحالي.",
    "Clue 3": "لعبت مع المنتخب في 2 كأس عالم و2 أمم، ولعبت 3 كأس عالم للأندية.",
    "Clue 4": "فزت بخمسة دوريات وست بطولات قارية مع جميع الفرق التي لعبت بها.",
    "Clue 5": "كنت كابتن فريقي القديم وسجلت مع فريقي الحالي 33 هدفًا في 8 مواسم. كنت هداف الدوري مع فريقي القديم في آخر موسم لعبت فيه معهم، وفي ثالث موسم مع فريقي الجديد كنت هداف الفريق في الدوري رغم أنني لست مهاجمًا."
  },
  {
    "name": "Ali Maaloul",
    "Clue 1": "لعب في دوريين من الدوريات الخمسة الكبرى، وأول بطولة فزت بها كانت خارج أوروبا.",
    "Clue 2": "لعبت لثلاثة أندية مختلفة من نفس الدوري الذي ألعب فيه حاليًا.",
    "Clue 3": "في مسيرتي مع الأندية لم أفز سوى ببطولتين، واحدة خارج أوروبا والأخرى مع جوزيه مورينيو.",
    "Clue 4": "كنت وصيفًا في الدوري الأوروبي مرة.",
    "Clue 5": "لعبت لكل الفئات العمرية للمنتخب وفزت معهم ببرونزية كأس القارات."
  },
  {
    "name": "Stephan El Shaarawy",
    "Clue 1": "لعبت في خمس دوريات خلال مسيرتي، منهم ثلاث في الدوريات الخمسة الكبرى.",
    "Clue 2": "فزت بدوريين فقط من الثلاثة في الدوريات الخمسة الكبرى التي لعبت فيها.",
    "Clue 3": "لعبت مع (رومارينهو، كامبل، فيليبي كايسيدو، ويليان، صامويل إيتو، بتشواي، ماريو ليمينا، أدان، باريخو، كريسبو، سيندروس).",
    "Clue 4": "الخمسة دوريات التي لعبت فيها هي: أربعة في أوروبا (منها ثلاث في الدوريات الكبرى) ودوري عربي. لعبت على الأقل في فريقين في كل دوري ما عدا الدوري العربي لعبت فيه لفريق واحد.",
    "Clue 5": "أنا من أشهر لاعبي الوسط الدفاعيين في تاريخ فرنسا، رغم أنني لم أفز بأي بطولة مع المنتخب."
  },{
    "name": "Saúl Ñíguez",
    "Clue 1": "فاز بدوري واحد، سوبر واحد، يوروبا واحد، كأس عالم أندية واحد، وسوبر أوروبي واحد.",
    "Clue 2": "لعبت لكل الفئات العمرية لمنتخب بلادي.",
    "Clue 3": "وصلت إلى ثلاث نهائيات قارية مع منتخب بلادي في ثلاث فئات عمرية مختلفة، وكسبت واحدًا فقط.",
    "Clue 4": "بدأت مسيرتي الاحترافية في 2012 وتم استدعائي للمنتخب الأول لأول مرة في 2016، وسجلت ثلاثة أهداف في 19 مباراة.",
    "Clue 5": "في منتصف مسيرتي فجأة انتقلت إلى فريق ولعبت معهم موسمًا كقلب دفاع رغم أن هذا ليس مركزي. أكبر إنجازاتي في دوري الأبطال هو كوني وصيف دوري أبطال أوروبا في إحدى السنوات. أنا من ناشئي ريال مدريد ولعبت في مسيرتي في دوريين أوروبيين فقط."
  },
  {
    "name": "Lassana Diarra",
    "Clue 1": "لعبت في خمس دوريات خلال مسيرتي، منهم ثلاث في الدوريات الخمسة الكبرى.",
    "Clue 2": "فزت بدوريين فقط من الثلاثة في الدوريات الخمسة الكبرى التي لعبت فيها.",
    "Clue 3": "لعبت مع (رومارينهو، كامبل، فيليبي كايسيدو، ويليان، صامويل إيتو، بتشواي، ماريو ليمينا، أدان، باريخو، كريسبو، سيندروس).",
    "Clue 4": "الخمسة دوريات التي لعبت فيها هي: أربعة في أوروبا (منها ثلاث في الدوريات الكبرى) ودوري عربي. لعبت على الأقل في فريقين في كل دوري ما عدا الدوري العربي لعبت فيه لفريق واحد.",
    "Clue 5": "أنا من أشهر لاعبي الوسط الدفاعيين في تاريخ فرنسا، رغم أنني لم أفز بأي بطولة مع المنتخب."
  },  {
    "name": "أيمن حفني",
    "Clue 1": "لعب كصانع ألعاب وكان معروفًا بمهاراته.",
    "Clue 2": "فاز بالدوري المصري الممتاز مرتين، وكأس مصر ثلاث مرات، وكأس الكونفيدرالية.",
    "Clue 3": "لعب مع أحمد توفيق، أحمد عيد عبد الملك، إبراهيم صلاح، وعمر جابر.",
    "Clue 4": "سجل هدفًا ضد الأهلي في 2014.",
    "Clue 5": "بدأ مسيرته في مكسا وتم التعرف عليه في الأهلي طرابلس.",
  },
  {
    "name": "رونالدينيو",
    "Clue 1": "لعب مع ماوريسيو بوكيتينو، فيكتور فالديس، ليليان تورام، تييري هنري، كافو، وجوليو سيزار.",
    "Clue 2": "اعتزل في 2018.",
    "Clue 3": "فاز بكأس العالم مرة، دوري أبطال أوروبا مرة، لقبين في الدوري الإسباني، ولقب واحد في الدوري الإيطالي.",
    "Clue 4": "تم إدراجه في قائمة FIFA 100 لأعظم اللاعبين الأحياء في 2004.",
    "Clue 5": "له هدف مميز ضد تشيلسي. فاز بجائزة الكرة الذهبية مرة واحدة.",
  },
  {
    "name": "ريكاردو كارفاليو",
    "Clue 1": "لعب مع كريستيانو رونالدو، ديكو، جون تيري، فابينيو، كواريسما، ديدييه دروغبا، مسعود أوزيل، توماس ليمار.",
    "Clue 2": "فاز بالدوري الإنجليزي وكأس الاتحاد ثلاث مرات مع تشيلسي.",
    "Clue 3": "فاز بالدوري الإسباني وكأس إسبانيا مع ريال مدريد مرة.",
    "Clue 4": "فاز بالدوري البرتغالي مرتين مع بورتو ودوري أبطال أوروبا مرة مع بورتو.",
    "Clue 5": "كان لاعبًا رئيسيًا في فوز البرتغال ببطولة اليورو 2016 وتم اختياره كأفضل لاعب برتغالي في 2003. لعب كمدافع مركزي (CB).",
  },
  {
    "name": "ديميتار بيرباتوف",
    "Clue 1": "لعب لنادي باير ليفركوزن، توتنهام، مانشستر يونايتد، فولهام، وموناكو.",
    "Clue 2": "اعتزل في 2019، وسجل 94 هدفًا و47 تمريرة حاسمة في الدوري الإنجليزي.",
    "Clue 3": "فاز بجائزة هداف الدوري الإنجليزي في موسم 2010/2011 بـ 20 هدفًا.",
    "Clue 4": "فاز بالدوري الإنجليزي مرتين مع مانشستر يونايتد (2008/09 و2010/11).",
    "Clue 5": "تم اختياره كأفضل لاعب بلغاري سبع مرات.",
  },
  {
    "name": "خالد الغندور",
    "Clue 1": "لعب مع أحمد شوبير، حازم إمام، أيمن منصور، حسام حسن، هاني رمزي، وعبد الواجد السيد.",
    "Clue 2": "بدأ وانتهى مسيرته في الزمالك، مع فترة ملحوظة في نادي كاظمة الكويتي.",
    "Clue 3": "كان من أكثر لاعبي الزمالك نجاحًا، وفاز بالدوري المصري، كأس أفريقيا، كأس السوبر الأفريقي، البطولة العربية للأندية، وكأس السوبر المصري السعودي.",
    "Clue 4": "معروف بلقب \"المدافع الأسطوري\".",
    "Clue 5": "يعد من أكثر قائدي الفريق فوزاً بالبطولات في تاريخ نادي الزمالك",
  },
  {
    "name": "إسلام الشاطر",
    "Clue 1": "لعب لنادي بتروجيت، الإسماعيلي، الزمالك، والأهلي.",
    "Clue 2": "كانت له مسيرة بارزة في السعودية مع اتحاد جدة.",
    "Clue 3": "اللاعب الوحيد في تاريخ كرة القدم المصرية الذي فاز بالدوري المصري مع ثلاثة فرق مختلفة.",
    "Clue 4": "انتقل إلى حرس الحدود بعد قرار مفاجئ من مانويل جوزيه وفاز معهم بكأس مصر مرتين.",
    "Clue 5": "انتقل إلى الإعلام بعد اعتزاله وقدم برامج رياضية في عدة قنوات.",
  },
  {
    "name": "غابرييل باتيستوتا",
    "Clue 1": "لعب كمهاجم وبدأ مسيرته كلاعب كرة سلة.",
    "Clue 2": "لعب لأندية روما، إنتر، فيورنتينا، والعربي القطري.",
    "Clue 3": "اللاعب الوحيد الذي سجل هاتريك في كؤوس عالم مختلفة.",
    "Clue 4": "ثاني أعلى هداف للأرجنتين.",
    "Clue 5": "لعب للأرجنتين في 1998.",
  },
];



final List<Map<String, String>> Risk_data = [
  {"title": "مصر في امم افريقيا", "5q": "اكتر لاعب مصري لعب مباريات في البطولة", "5a": "احمد حسن","5c":"" , "10q": "كم مرة مصر وصلت للنهائي", "10a": "10" ,"10c":"", "20q": "من المصري الوحيد اللي سجل اكتر من هاتريك", "20c": "محمد مرسي حسين - حسن الشاذلي - احمد حسن - علي ابو جريشة" , "20a": "حسن الشاذلي" , "40q": "من صاحب اسرع هدف في تاريخ مصر وكان قصاد الجابون", "40c": "ايمن منصور - جمال حمزة - ابراهيم عبدالخالق - مالك عبدالحميد" , "40a": "ايمن منصور"},
  {"title": "ميلانو", "5q": "اذكر 3 لاعبين لعبوا للفريقين", "5a": "في كتير" ,"5c":"", "10q": "هداف الديربي", "10a": "شيفنشبكو" ,"10c":"", "20q": "لعبوا 6 ماتشات في دوري الابطال .. الانتر كسب كام ماتش", "20c": "1-2-3-4" , "20a": "2" , "40q": "اكبر انتصار في الدريبي كان سنة 2001 .. كان كام كام؟", "40c": "6:0 - 5:1 - 5:0 - 7:2" , "40a": "6:0"},
  {"title": "بالون دور", "5q": "اكتر لاعب اترشح للجائزة؟", "5a": "رونالدو" ,"5c":"", "10q": "اول لاعب توج بالجائزة 3 مرات", "10a": "كرويف" ,"10c":"", "20q": "من اكتر لاعب اتشرح للجائزة (13 مرة) ومأخدش الجايزة", "20c": "مالديني - ابراهيموفيتش - جون تيري - انيستا" , "20a": "مالديني" , "40q": "اكتر لاعب اترشح للجايزة ومأخدش ولا صوت", "40c": "فاردي - بول سكولز - جيمي كاريجار - فابريجاس" , "40a": "بول سكولز"},
  {"title": "اسيا", "5q": "اكتر لاعب حصل علي جائزة افضل لاع اسيوي", "5a": "سون" ,"5c":"", "10q": "اكتر منتخب اخد كأس اسيا", "10a": "اليابان" ,"10c":"", "20q": "ما هي الدولة اللي اترشح منها لاعب للبالون دور سنة 2007", "20c": "اليابان - العراق - السعودية -كوريا الجنوبية" , "20a": "العراق" , "40q": "من ثاني اكثر لاعب سجل اهداف في كأس اسيا", "40c": "علي دائي - عبدالمعز علي - لي دونج جووك - ساردار ازمون" , "40a": "المعز علي"},
  {"title": "لندن", "5q": "اذكر مدرب درب فرقتين في لندن", "5a": "بوتشيتينو" ,"5c":"", "10q": "اكتر فريق انتصر في دربيات لندن", "10a": "ارسنال" ,"10c":"", "20q": "لاعب لعب ل ارسنال وتوتنهام و تشيلسي", "20c": "اديبايور - ايان رايت - ويلي يونج - ويليام جالاس" , "20a": "ويليام جالاس" , "40q": "كم لاعب برازيلي لعب ل ارسنال وتشيلسي", "40c": "2 - 3 - 5 - 6" , "40a": "2"},
  {"title": "روبرتو باجيو", "5q": "ضيع ضرة الجزاء الشهيرة قصاد مين", "5a": "البرازيل" ,"5c":"", "10q": "كم مرة كان في اول 3 مراكز للبالون دور","10c":"", "10a": "مرتين" , "20q": "كسب الحذاء الذهبي لكأس ابطال الكؤوس لما كان بيلعب مع انهي فريق", "20c": "ميلان - اانتر - يوفنتوس - بولونيا" , "20a": "يوفنتوس" , "40q": "كم مرة فاز بالدوري الايطالي", "40c": "0 - 2 - 3 - 4" , "40a": "2"},
  {"title": "", "5q": "","5c":"" , "5a": "", "10q": "","10c":"", "10a": "" , "20q": "", "20c": "" , "20a": "" , "40q": "", "40c": "" , "40a": ""},
];


final List<Map<String, String>> labesSa7bak_data = [
  {"question": "اذكر 5 ملاعب في اسبانيا", },
  {"question": "اذكر 5 لاعبين مصريين شاركوا في كاس العالم", },
  {"question": "اذكر 5 فرق افريقية غير عربية", },
  {"question": "اذكر 5 لاعبين لعبوا ل برشلونة و مانشتسر سيتي", },
  {"question": "اذكر5  فرق الطقم الاساسي مخطط", },
  {"question": "اذكر 5 اسامي ملاعب في انجلترا", },
  {"question": "اذكر 5 اسماء دول كسبت كاس اسيا", },
  {"question": "اذكر 5 فرق كسبت دوري الابطال وليست من الدوريات الخمسة الكبري", },
  {"question": "اذكر 5 لاعبين انجليز لعبوا بره انجلترا", },
  {"question": "اذكر 5 لاعبين من كوريا الجنوبية", },
  {"question": "اذكر 5 دول خسرت من الارجنتين في كاس العالم 2022", },
  {"question": "اذكر 5 لاعبين حصلوا علي دوري الابطال مع فرقتين مختلفتين", },
  {"question": "اذكر 5 لاعبين لعبوا ل3 فرق او اكتر في نفس الدوري", },
  {"question": "اذكر 5 لاعبين انتقلوا من الدوري الانجليزي ل ريال مدريد", },
  {"question": "اذكر 5 لاعبين انتقلوا من الدوري الانجليزي ل برشلونة", },
  {"question": "اذكر 5 فرق دربهم مورينيو", },
  {"question": "اذكر 5 لاعبين لعبوا كورة و ابنهم لعب كورة", },
];


final List<Map<String, String>> Bank_data = [
  {"question": "امتي كانت اول مرة الاهلي ياخد الدوري من غير هزيمة؟", "answer": "1976"},
  {"question": "كام لاعب جاب 100+ جون في البريميرليج؟", "answer": "34"},
  {"question": "هازارد سجل كام جون مع المنتخب؟", "answer": "33"},
  {"question": "دينس بيركامب عمل كام اسيست في البريميرليج؟", "answer": "94"},
  {"question": "بيتر تشيك عمل كام سيف في الدوري الانجليزي؟", "answer": "1005"},
  {"question": "لامبارد جاب كام بلن مع تشيلسي في الدوري الانجليزي؟", "answer": "32"},
  {"question": "ماكسويل اخد كام بطولة؟", "answer": "37"},
  {"question": "مجموع الفلوس في انتقالات دي ماريا؟", "answer": "179"},
  {"question": "هاندانوفيتش لعب كام ماتش مع انتر ميلان؟", "answer": "455"},
  {"question": "البرازيل لعبت كام ماتش في كاس العالم؟", "answer": "114"},
  {"question": "اكبر انتصار في كاس العالم كان للمجر علي الهندوراس 10-1 كان سنة كام؟", "answer": "1982"},
  {"question": "اكتر عدد اهداف سجله منتخب في بطولة واحدة من كاس العالم؟", "answer": "27"},
  {"question": "اكتر saves في ماتش واحد كانت لتيم هاورد كانوا كام save ؟", "answer": "16"},
  {"question": "ايه اكبر عدد مرات متتالية ريال مدريد اخد فيها الدوري ؟", "answer": "5"},
  {"question": "بوردو أخدوا كام دوري ؟", "answer": "6"},
  {"question": "ديبورتيفولاكرونيا اكتر فريق اتعادل في موسم في الدوري الاسباني سنة 2016 كانوا كام؟", "answer": "18"},
  {"question": "اطول سلسلة لا هزيمة في الدوري الاسباني كام ماتش؟", "answer": "43"},
  {"question": "ميسي سجل قصاد كام فريق في الدوري الاسباني؟", "answer": "38"},
  {"question": "رونالدو وصل ل300 هدف في الدوري الاسباني في كام ماتش؟", "answer": "286"},
  {"question": "اكتر عدد مباريات متتالي لميسي يسجل فيه هدف علي الاقل؟", "answer": "21"},
  {"question": "ميسي جاب كام هاتريك في الدوري الاسباني؟", "answer": "36"},
  {"question": "دي خيا أخد كام بطولة مع اليونايتد (من غير الكومينتي) ؟", "answer": "5"},
  {"question": "ميسي سجل اكتر من 30 جون في الدوري كام مرة؟", "answer": "8"},
  {"question": "ديجو الفيس حارس اشبيلية اكتر حارس صد بلنتيات في موسم واحد في الدوري كانوا كام؟", "answer": "6"},
  {"question": "راموس اخد كام كارت احمر؟", "answer": "20"},
  {"question": "سواريز جاب كام جون في الدوري الاسباني؟", "answer": "179"},
  {"question": "كام لاعب سجل اكتر من 35 جون في الدوري الاسباني في موسم واحد؟", "answer": "6"},
  {"question": "توني كروس لعب كام ماتش في كأس العالم للاندية؟", "answer": "11"},
  {"question": "حسام حسن اخد كام دوري؟", "answer": "15"},
  {"question": "بوشكاش جاب كام جون ؟", "answer": "806"},
  {"question": "احمد حسن لعب كام ماتش مع المنتخب؟", "answer": "184"},
  {"question": "كاسياس عنده كام كلين شيت دولي؟", "answer": "102"},
  ];