final List<Map<String, String>> Men_fe_elsora_data = [
  {"title": "Spurs vs Atletico Madrid",
    "image": "https://i2-prod.mirror.co.uk/incoming/article8521039.ece/ALTERNATES/s1227b/Atletico-Madrid-v-Tottenham-Hotspur-International-Champions-Cup.jpg",
    "player1":"Vorm",
    "player2":"Trippier",
    "player3":"Walkes",
    "player4":"Carter-Vickers",
    "player5":"Yedlin",
    "player6":"Wanyama",
    "player7":"Winks",
    "player8":"Lamela",
    "player9":"Eriksen",
    "player10":"Onomah",
    "player11":"Janssen",
  },
  {"title": "Atletico Madrid vs Spurs 2016",
    "image": "https://drive.google.com/uc?export=view&id=1Hxa9Q6IU5agcT1_GIFqIUty3frsPTBgc",
    "player1":"J Oblak",
    "player2":"S Vrsaljko",
    "player3":"S Savic",
    "player4":"D Godín",
    "player5":"Filipe Luis",
    "player6":"S Ñíguez",
    "player7":"G Fernández",
    "player8":"Tiago Mendes",
    "player9":"T Partey",
    "player10":"H Hernández ",
    "player11":"F Torres",
  },
  {
    "title": "England vs Malta. World Cup Qualification 2016",
    "image": "https://e0.365dm.com/16/10/1600x900/skysports-england-malta-qualifiers-team_3803972.jpg?20161008174041",
    "player3": "Joe Hart",
    "player1": "Kyle Walker",
    "player6": "Ryan Bertrand",
    "player4": "Jordan Henderson",
    "player2": "Gary Cahill",
    "player5": "John Stones",
    "player8": "Theo Walcott",
    "player7": "Dele Alli",
    "player11": "Daniel Sturridge",
    "player9": "Wayne Rooney (C)",
    "player10": "Jesse Lingard"
  },
  {
    "title": "Arsenal Invincibles",
    "image": "https://miro.medium.com/v2/resize:fit:1024/1*cAh590d1845W979mOeyT_g.jpeg",
    "player1": "Viera",
    "player2": "Bergkamp",
    "player3": "Edu",
    "player4": "Gasper",
    "player5": "Lauren",
    "player6": "Campbell",
    "player7": "Toure",
    "player8": "Cole",
    "player9": "Lumberg",
    "player10": "Henry",
    "player11": "Pires"
  },
  {
    "title": "Saudi Arabia Vs Argentina",
    "image": "https://sm.imgix.net/22/46/saudi-arabia_2.jpg",
    "player1": "محمد العويس",
    "player2": "سعود عبدالحميد",
    "player3": "حسان التمبكتي",
    "player4": "علي البليهي",
    "player5": "ياسر الشهراني",
    "player6": "عبدالإله المالكي",
    "player7": "محمد كنو",
    "player8": "فراس البريكان",
    "player9": "سلمان الفرج",
    "player10": "سالم الدوسري",
    "player11": "صالح الشهري"
  },
  {
    "title": "Man city vs Bayern Munich 2014 UCL",
    "image": "https://media.gettyimages.com/id/459581250/photo/fbl-eur-c1-man-city-bayern-munich.jpg?s=2048x2048&w=gi&k=20&c=SoXZUIGhb-cnnGo-Hv_6pf6CQ3uZvfK9-ccUsbc0x14=",
    "player1": "Fernando",
    "player2": "Joe Hart",
    "player3": "Eliaquim Mangala",
    "player4": "Vincent Kompany",
    "player5": "Frank Lampard",
    "player6": "James Milner",
    "player7": "Bacary Sagna",
    "player8": "Jesus Navas",
    "player9": "Gael Clichy",
    "player10": "Samir Nasri",
    "player11": "Sergio Aguero"
  },{
    "title": "Arsenal vs Schalke 04 2012 UCL",
    "image": "https://drive.google.com/uc?export=view&id=1Sy8obXSN3s1cA2yH6k8bpJc6L_6Y6yKw",
    "player1": "Vito Mannone",
    "player2": "Per Mertesacker",
    "player3": "Clarindo Andre Santos",
    "player4": "Carl Jenkinson",
    "player5": "Yao Gervinho",
    "player6": "Lukas Podolski",
    "player7": "Francis Coquelin",
    "player8": "Mikel Arteta",
    "player9": "Santi Cazorla",
    "player10": "Aaron Ramsey",
    "player11": "Thomas Vermaelen"
  },
  {
    "title": "Italy vs Bosnia Friendly 2024",
    "image": "https://drive.google.com/uc?export=view&id=1nOrqtkia3f-sNiqq5nBOZH35c0g-dC_J",
    "player1": "1C Donnarumma",
    "player2": "4 Buongiorno",
    "player3": "5 Calafiori",
    "player4": "7 Frattesi",
    "player5": "8 Jorginho",
    "player6": "9 Scamacca",
    "player7": "13 Darmian",
    "player8": "14 Chiesa",
    "player9": "15 Bellanova",
    "player10": "21 Fagioli",
    "player11": "24 Cambiaso"
  },
  {
    "title": "Belgium v Wales UEFA Nations League 2022",
    "image": "https://drive.google.com/uc?export=view&id=1iupKasRiRl7pcSSFFm5eWQLHk_FJVHTD",
    "player1": "13 K Casteels",
    "player2": "19 L Dendoncker",
    "player3": "4 D Boyata",
    "player4": "3 A Theate",
    "player5": "15 T Meunier",
    "player6": "6 A Witsel",
    "player7": "8 Y Tielemans",
    "player8": "11 Y Carrasco",
    "player9": "7 K De Bruyne (c)",
    "player10": "17 L Trossard",
    "player11": "23 M Batshuayi"
  },
  {
    "title": "Morocco Vs USA 2022",
    "image": "https://media.gettyimages.com/id/1401073803/photo/morocco-v-united-states.jpg?s=1024x1024&w=gi&k=20&c=MGd3S4anYLiPSkXa-BstAzO-HvUT253ldoNT15QHT2E=",
    "player1": "1 bono",
    "player2": "2 Hakimi",
    "player3": "23 S Mmaee",
    "player4": "6  Saiss",
    "player5": "5 Aguerd",
    "player6": "3 A Masina",
    "player7": "4 Amrabet",
    "player8": "7 Ounahi",
    "player9": "8 Taarabt",
    "player10": "9 Tissoudali",
    "player11": "17 el kaabi"
  },
  {
    "title": " Napoli v Juventus Serie A 2023",
    "image": "https://media.gettyimages.com/id/1838644904/photo/players-of-ssc-napoli-pose-for-a-team-photo-prior-to-the.jpg?s=1024x1024&w=gi&k=20&c=TieM_Hp5kUCz8RJhiIJmjmq2hp02rYckmNdTnsSga6g=",
    "player1": "1 Alex Meret",
    "player2": "5 Juan Jesus",
    "player3": "3 Kim Min-Jae",
    "player4": "17 Mathías Olivera",
    "player5": "22 Giovanni Di Lorenzo",
    "player6": "68 Stanislav Lobotka",
    "player7": "91 Tanguy Ndombele",
    "player8": "99 André-Frank Zambo Anguissa",
    "player9": "9 Victor Osimhen",
    "player10": "77 Khvicha Kvaratskhelia",
    "player11": "11 Hirving Lozano"
  },
  {
    "title": "Qatar v Senegal 2022",
    "image": "https://www.idiskitimes.co.za/wp-content/uploads/2022/11/Qatar-XI-768x512.jpg",
    "player1": "Meshaal Aissa Barsham",
    "player2": "17 I. Mohammed",
    "player3": "2 P. Miguel",
    "player4": "16 B. Khoukhi",
    "player5": "3 A. Hassan",
    "player6": "14 H. Ahmed",
    "player7": "12 Karim Boudiaf",
    "player8": "10 (c) Hassan Al Haydos",
    "player9": "23 Assim Madibo",
    "player10": "19 Almoez Ali",
    "player11": "11 Akram Afif"
  },
  {
    "title": "Sweden v Estonia Euro 2024 Qual.",
    "image": "https://media.gettyimages.com/id/1791410276/photo/group-f-uefa-euro-2024-european-qualifiers.jpg?s=2048x2048&w=gi&k=20&c=IuCP4lVqhb0D7UF0NvTeTWLmyVu2n8NKyt4XLUpJnXs=",
    "player1": "Robin Olsen",
    "player2": "Filip Helander",
    "player3": "Viktor Gyokeres",
    "player4": "Albin Ekdal",
    "player5": "Victor Lindelof",
    "player6": "Jens Cajuste",
    "player7": "Dajen Kulusevski",
    "player8": "Emil Forsberg",
    "player9": "Ludwig Augustinsson",
    "player10": "Viktor Claesson",
    "player11": "Emil Krafth"
  },
  {
    "title": "England v Scotland Friendly 2013",
    "image": "http://www.englandfootballonline.com/images/Matches/M921Sco2013Eng.jpg",
    "player1": "Theo Walcott",
    "player2": "Kyle Walker",
    "player3": "Phil Jagielka",
    "player4": "Danny Welbeck",
    "player5": "Joe Hart",
    "player6": "Gary Cahill",
    "player7": "Wayne Rooney",
    "player8": "Tom Cleverley",
    "player9": "Steven Gerrard",
    "player10": "Leighton Baines",
    "player11": "Jack Wilshere"
  },
  {
    "title": "Liverpool Real Madrid UCL 2014",
    "image": "https://images2.minutemediacdn.com/image/upload/c_fill,w_1440,ar_16:9,f_auto,q_auto,g_auto/shape/cover/sport/Real-Madrid-CF-v-Liverpool-FC---UEFA-Champions-Lea-e0d34eb6a77baf9ee3448a6dd728e21e.jpg",
    "player1": "Alberto Moreno",
    "player2": "Dejan Lovren",
    "player3": "Martin Skrtel",
    "player4": "Simon Mignolet",
    "player5": "Jordan Henderson",
    "player6": "Philippe Coutinho",
    "player7": "Mario Balotelli",
    "player8": "Steven Gerrard",
    "player9": "Glen Johnson",
    "player10": "Joe Allen",
    "player11": "Raheem Sterling"
  },
  {
    "title": "Tottenham Hotspur v Chicago Fire Friendly 2014",
    "image": "https://media.gettyimages.com/id/452816772/photo/tottenham-hotspur-v-chicago-fire.jpg?s=1024x1024&w=gi&k=20&c=BJvGx0fQ1q25cQBbtdlzHhIMf13lCY6bYCN-j-06SD0=",
    "player1": "Andros Townsend ",
    "player2": "Brad Friedel ",
    "player3": "Etienne Capoue ",
    "player4": "Milos Veljkovic",
    "player5": "Michael Dawson ",
    "player6": "Harry Kane ",
    "player7": "Erik Lamela ",
    "player8": "Lewis Holtby ",
    "player9": "Ryan Mason ",
    "player10": "Danny Rose",
    "player11": "Kyle Walker "
  },{
    "title": "PSG v Chelsea UCL 2016",
    "image": "https://media.gettyimages.com/id/514535492/photo/fbl-eur-c1-chelsea-psg.jpg?s=1024x1024&w=gi&k=20&c=d2DrfwNtLDyaVu1qYHLY2pkw6AA8ck0AlL4CjnaNY0U=",
    "player1": "Thiago Silva",
    "player2": "David Luiz",
    "player3": "Thiago Motta",
    "player4": "Adrien Rabiot",
    "player5": "Zlatan Ibrahimovic",
    "player6": "Kevin Trapp",
    "player7": "Marquinhos",
    "player8": "Angel Di Maria",
    "player9": "Maxwell",
    "player10": "Blaise Matuidi",
    "player11": "Lucas Moura"
  },
  {
    "title": "Portugal v Luxembourg Euro Qual. 2019",
    "image": "https://media.gettyimages.com/id/1175346096/photo/portugal-v-luxembourg-uefa-euro-2020-qualifier.jpg?s=1024x1024&w=gi&k=20&c=bsg_Obvf6IiY_5awYZcnAZi4q4qC10QBG8OWflHxKbQ=",
    "player1": "1 Rui Patrício",
    "player2": "2 Nélson Semedo",
    "player3": "3 Pepe",
    "player4": "4 Rúben Dias",
    "player5": "5 Guerreiro",
    "player6": "7 C Ronaldo",
    "player7": "8 João Moutinho",
    "player8": "13 Danilo",
    "player9": "16 Bruno Fernandes",
    "player10": "23 João Felix",
    "player11": "20 Bernardo Silva"
  },{
    "title": " Portugal v Czech Republic Euro 2008 ",
    "image": "https://l450v.alamy.com/450v/2e526c0/portugal-team-during-the-euro-2008-uefa-championships-soccer-match-group-a-portugal-vs-czech-republic-at-stade-de-geneve-in-geneva-switzerland-on-june-11-2008-portugal-won-3-1-photo-by-steeve-mcmaycameleonabacapresscom-2e526c0.jpg",
    "player1": "Ricardo",
    "player2": "Ricardo Carvalho",
    "player3": "Nuno Gomes",
    "player4": "Petit",
    "player5": "Pepe",
    "player6": "Cristiano Ronaldo",
    "player7": "Joao Moutinho",
    "player8": "Jose Bosingwa",
    "player9": "Deco",
    "player10": "Paulo Ferreira",
    "player11": "Simao Sabrosa"
  },{
    "title": "Germany v Netherlands 2024",
    "image": "https://media.gettyimages.com/id/2107853661/photo/germany-netherlands.jpg",
    "player1": "Jamal Musiala",
    "player2": "Robert Andrich",
    "player3": "Joshua Kimmich",
    "player4": "Florian Wirtz",
    "player5": "Ilkay Gündogan",
    "player6": "Marc-André ter Stegen",
    "player7": "Antonio Rüdiger",
    "player8": "Toni Kroos",
    "player9": "Kai Havertz",
    "player10": "Jonathan Tah",
    "player11": "Maximilian Mittelstädt"
  },{
    "title": "Denmark v Australia WC 2022",
    "image": "https://media.gettyimages.com/id/1445767800/photo/group-d-fifa-world-cup-qatar-2022.jpg?s=2048x2048&w=gi&k=20&c=tly-R2sQkFXEg8j6-MSiiaNjRgpHEsJpR1fs4iq9COk=",
    "player1": "Rasmus Kristensen",
    "player2": "Joachim Andersen",
    "player3": "Andreas Christensen",
    "player4": "Andreas Skov Olsen",
    "player5": "Pierre-Emil Hojbjerg",
    "player6": "Kasper Schmeichel",
    "player7": "Joakim Maehle",
    "player8": "Mathias Jensen",
    "player9": "Jesper Lindström",
    "player10": "Christian Eriksen",
    "player11": "Martin Braithwaite"
  },{
    "title": "Portugal v Finland Friendly 2024",
    "image": "https://media.gettyimages.com/id/1175346096/photo/portugal-v-luxembourg-uefa-euro-2020-qualifier.jpg?s=1024x1024&w=gi&k=20&c=bsg_Obvf6IiY_5awYZcnAZi4q4qC10QBG8OWflHxKbQ=",
    "player1": "Ruben Dias",
    "player2": "Rafael Leao",
    "player3": "Antonio Silva",
    "player4": "Joao Palhinha",
    "player5": "Diogo Jota",
    "player6": "Jose Sa",
    "player7": "Joao Cancelo",
    "player8": "Nuno Mendes",
    "player9": "Vitinha",
    "player10": "Joao Neves",
    "player11": "Francisco Conceicao"
  },{
    "title": "Arsenal v Monaco UCL 2015",
    "image": "https://drive.google.com/uc?export=view&id=1jJsEkXkhvpHSnxCkT5sZjTlt-oCEopzP",
    "player1": "Hector Bellerin",
    "player2": "David Ospina",
    "player3": "Per Mertesacker",
    "player4": "Laurent Koscielny",
    "player5": "Danny Welbeck",
    "player6": "Olivier Giroud",
    "player7": "Alexis Sanchez",
    "player8": "Kieran Gibbs",
    "player9": "Santi Cazorla",
    "player10": "Francis Coquelin",
    "player11": "Mesut Ozil"
  },{
    "title": "Man United v Bayern Munich UCL 2014",
    "image": "https://media.gettyimages.com/id/481873825/photo/fbl-eur-c1-man-utd-bayern-munich.jpg?s=1024x1024&w=gi&k=20&c=qHZTEGu8poTJchtvFdn9dI4sEsQgysxSq2NkaMsMBeI=",
    "player1": "David de Gea",
    "player2": "Phil Jones",
    "player3": "Marouane Fellaini",
    "player4": "Rio Ferdinand",
    "player5": "Danny Welbeck",
    "player6": "Nemanja Vidic",
    "player7": "Ryan Giggs",
    "player8": "Wayne Rooney",
    "player9": "Michael Carrick",
    "player10": "Antonio Valencia",
    "player11": "Alexander Buttner"
  },
  {
    "title": "Bayern Munich v Man United UCL 2014",
    "image": "https://drive.google.com/uc?export=view&id=1zxGg1cwZAJJFqdG_i3-FgS7OTav-QxUG",
    "player1": "David Alaba",
    "player2": "Manuel Neuer",
    "player3": "Javier Martinez",
    "player4": "Toni Kroos",
    "player5": "Thomas Mueller",
    "player6": "Jerome Boateng",
    "player7": "Philipp Lahm",
    "player8": "Arjen Robben",
    "player9": "Franck Ribery",
    "player10": "Rafinha",
    "player11": "Bastian Schweinsteiger"
  },{
    "title": "Germany v Portugal Euro 2021",
    "image": "https://media.gettyimages.com/id/1233544009/photo/fbl-euro-2020-2021-match24-por-ger.jpg?s=1024x1024&w=gi&k=20&c=e9QIeJIAC7VWaPsgX8Y3-NPYDFye1qSQ91XuTpkM0kc=",
    "player1": "Manuel Neuer",
    "player2": "Toni Kroos",
    "player3": "Antonio Ruediger",
    "player4": "Mats Hummels",
    "player5": "Matthias Ginter",
    "player6": "Kai Havertz",
    "player7": "Joshua Kimmich",
    "player8": "Robin Gosens",
    "player9": "Ilkay Gundogan",
    "player10": "Thomas Mueller",
    "player11": "Serge Gnabry"
  },
  {
    "title": "Denmark v Australia WC 2018",
    "image": "https://drive.google.com/uc?export=view&id=1IsHULeCWXGY7PfsNgkyIESxSXLzyAsrA",
    "player1": "Kasper Schmeichel",
    "player2": "Yussuf Poulsen",
    "player3": "Henrik Dalsgaard",
    "player4": "Nicolai Jorgensen",
    "player5": "Andreas Christensen",
    "player6": "Simon Kjaer",
    "player7": "Pione Sisto",
    "player8": "Jens Stryger Larsen",
    "player9": "Lasse Schone",
    "player10": "Christian Eriksen",
    "player11": "Thomas Delaney"
  },{
    "title": "Chelsea V PSG UCL 2014",
    "image": "https://media.gettyimages.com/id/483412697/photo/fbl-eur-c1-chelsea-psg.jpg?s=1024x1024&w=gi&k=20&c=-CIDEInQrva4zafxqL4gXDT0DnoJHEYvnUFKbBXMLKg=",
    "player1": "David Luiz",
    "player2": "Petr Cech",
    "player3": "Branislav Ivanovic",
    "player4": "John Terry",
    "player5": "Gary Cahill",
    "player6": "Frank Lampard",
    "player7": "Cesar Azpilicueta",
    "player8": "Oscar",
    "player9": "Eden Hazard",
    "player10": "Willian",
    "player11": "Samuel Eto'o"
  },{
    "title": "Internazionale v Atletico Madrid UCL 2024  ",
    "image": "https://drive.google.com/uc?export=view&id=1P_AkWeKYeQC67lmk9EaSjkVQmOFS3cMa",
    "player1": "Marcus Thuram",
    "player2": "Stefan de Vrij",
    "player3": "Denzel Dumfries",
    "player4": "Benjamin Pavard",
    "player5": "Yann Sommer",
    "player6": "Alessandro Bastoni",
    "player7": "Henrikh Mkhitaryan",
    "player8": "Federico Dimarco",
    "player9": "Lautaro Martinez",
    "player10": "Nicolo Barella",
    "player11": "Hakan Calhanoglu"
  },{
    "title": "Internazionale v Genoa CFC Serie A 2023",
    "image": "https://drive.google.com/uc?export=view&id=1k5dqsd-8SRuVOMtU31l2mHUg19iZFky5",
    "player1": "Marcus Thuram",
    "player2": "Francesco Acerbi",
    "player3": "Yann Bisseck",
    "player4": "Marko Arnautovic",
    "player5": "Yann Sommer",
    "player6": "Alessandro Bastoni",
    "player7": "Henrikh Mkhitaryan",
    "player8": "Matteo Darmian",
    "player9": "Carlos Augusto",
    "player10": "Nicolo Barella",
    "player11": "Hakan Calhanoglu"
  },
  {
    "title": "Juventus v Hellas Verona  Serie A 2022",
    "image": "https://drive.google.com/uc?export=view&id=17IPDpYF77b4jcUy5SHRFQVHxYkCjuzS0",
    "player1": "Adrien Rabiot",
    "player2": "Gleison Bremer",
    "player3": "Arkadiusz Milik",
    "player4": "Danilo",
    "player5": "Mattia Perin",
    "player6": "Leonardo Bonucci",
    "player7": "Moise Kean",
    "player8": "Filip Kostic",
    "player9": "Juan Cuadrado",
    "player10": "Manuel Locatelli",
    "player11": "Nicolo Fagioli"
  },{
    "title": "Netherlands v Ecuador WC 2022",
    "image": "https://drive.google.com/uc?export=view&id=158nUdQmt-p-ydPGm5l75VDD1IKFNttXa",
    "player1": "Andreis Noppert",
    "player2": "Nathan Ake",
    "player3": "Denzel Dumfries",
    "player4": "Daley Blind",
    "player5": "Virgil van Dijk",
    "player6": "Cody Gakpo",
    "player7": "Davy Klaassen",
    "player8": "Frankie de Jong",
    "player9": "Teun Koopmeiners",
    "player10": "Steven Bergwijn",
    "player11": "Jurrien Timber"
  },
  {
    "title": "Netherlands v France Euro 2024",
    "image": "https://drive.google.com/uc?export=view&id=1bwZ6-Mq_YgaiVd-zw89zy0wgBLmFuF7e",
    "player1": "Bart Verbruggen",
    "player2": "Jerdy Schouten",
    "player3": "Stefan de Vrij",
    "player4": "Denzel Dumfries",
    "player5": "Virgil van Dijk",
    "player6": "Cody Gakpo",
    "player7": "Jeremie Frimpong",
    "player8": "Tijjani Reijnders",
    "player9": "Nathan Ake",
    "player10": "Memphis Depay",
    "player11": "Xavi Simons"
  },
  {
    "title": "Germany vs Japan WC 2022",
    "image": "https://www.aljazeera.com/wp-content/uploads/2022/11/2022-11-23T131658Z_1800059963_UP1EIBN10A3HK_RTRMADP_3_SOCCER-WORLDCUP-GER-JPN-REPORT.jpg?resize=770%2C513&quality=80",
    "player1": "Raum",
    "player2": "Neuer",
    "player3": "Rudiger",
    "player4": "Havertz",
    "player5": "Sule",
    "player6": "Schlotterbeck",
    "player7": "Kimmich",
    "player8": "Musiala",
    "player9": "Gnabry",
    "player10": "Muller",
    "player11": "Gundogan"
  },
  {
    "title": "Germany vs Costa Rica WC 2022",
    "image": "https://media.gettyimages.com/id/1245279793/photo/world-cup-2022-costa-rica-germany.jpg?s=1024x1024&w=gi&k=20&c=eOZ-_eE6F0tli2Fzpzptr1rah7m9AaSyzpvSsq32DMI=",
    "player1": "Neuer",
    "player2": "Kimmich",
    "player3": "Rudiger",
    "player4": "Müller",
    "player5": "Goretzka",
    "player6": "Gnabry",
    "player7": "Süle",
    "player8": "Schlotterbeck",
    "player9": "Musiala",
    "player10": "Gündogan",
    "player11": "Sané"
  },
  {
    "title": "Italy and the Republic of Ireland Friendly 2014",
    "image": "https://drive.google.com/uc?export=view&id=185bqLEZS_V3YnSmkMGNP4Fr0XEX-MLK8",
    "player1": "Salvatore Sirigu",
    "player2": "Ciro Immobile",
    "player3": "Thiago Motta",
    "player4": "Matteo Darmian",
    "player5": "Gabriel Paletta",
    "player6": "Leonardo Bonucci",
    "player7": "Mattia De Sciglio",
    "player8": "Marco Verratti",
    "player9": "Giuseppe Rossi",
    "player10": "Claudio Marchisio",
    "player11": "Riccardo Montolivo"
  },{
    "title": "Internazionale v Venezia Seria A 2022",
    "image": "https://drive.google.com/uc?export=view&id=1cQjX4jd4qKUMwhLKFvmhH8l39OJniqDd",
    "player1": "Škriniar",
    "player2": "Darmian",
    "player3": "Bastonide",
    "player4": "Handanović",
    "player5": "Džeko",
    "player6": "Vrji",
    "player7": "Brozović",
    "player8": "Barellax",
    "player9": "Martínez",
    "player10": "Çalhanoğlu",
    "player11": "Perišić"
  },


  {
    "title": "Juventus v Bologna FC  Serie A 2023",
    "image": "https://drive.google.com/uc?export=view&id=1CqNa_0d5LqZpEuDL-NHa6jotBGLI5sdK",
    "player1": "Federico Chiesa",
    "player2": "Wojciech Szczesny",
    "player3": "Federico Gatti",
    "player4": "Arkadiusz Milik",
    "player5": "Adrien Rabiot",
    "player6": "Danilo",
    "player7": "Filip Kostic",
    "player8": "Manuel Locatelli",
    "player9": "Juan Cuadrado",
    "player10": "Nicolo Fagioli",
    "player11": "Alex Sandro"
  },
  {
    "title": "Porto v Inter Milan UCL 2023",
    "image": "https://media.gettyimages.com/id/1468690321/photo/fc-internazionale-v-fc-porto-round-of-16-leg-one-uefa-champions-league.jpg?s=2048x2048&w=gi&k=20&c=tdVvMzhocjuo7-TcTluoE_2tAkJTMJLqcfV7L4MG1e0=",
    "player1": "Pepe",
    "player2": "Diogo Costa",
    "player3": "Ivan Marcano",
    "player4": "Marko Grujić",
    "player5": "Zaidu",
    "player6": "Mehdi Taremi",
    "player7": "Matheus Uribe",
    "player8": "Galeno",
    "player9": "João Mário",
    "player10": "Otávio",
    "player11": "Pepe"
  },
  {
    "title": "SL Benfica v Olympique Marseille UEFA Europa League 24",
    "image": "https://media.gettyimages.com/id/2147728604/photo/sl-benfica-v-olympique-marseille-quarter-final-first-leg-uefa-europa-league-2023-24.jpg?s=1024x1024&w=gi&k=20&c=BL0XUbG-TRJ8-fHrB0R0Lk2DVYeqIv2a4l6JzaOZpds=",
    "player1": "Alexander Bah",
    "player2": "Antonio Silva",
    "player3": "Casper Tengstedt",
    "player4": "Anatoliy Trubin",
    "player5": "Nicolas Otamendi",
    "player6": "Angel Di Maria",
    "player7": "Rafa Silva",
    "player8": "David Neres",
    "player9": "Fredrik Aursnes",
    "player10": "Joao Neves",
    "player11": "Florentino Luis"
  },

  {
    "title": "Portugal v Ghana WC 2022",
    "image": "https://media.gettyimages.com/id/1245056270/photo/world-cup-2022-portugal-ghana.jpg?s=1024x1024&w=gi&k=20&c=ZTXTm_5_w9GAGu7kLUkDyksVy6KhYTRrZuv64lbLKL4=",
    "player1": "Diogo Costa",
    "player2": "Joao Cancelo",
    "player3": "Bernardo Silva",
    "player4": "Danilo Pereira",
    "player5": "Raphael Guerreiro",
    "player6": "Ruben Neves",
    "player7": "Otavio",
    "player8": "Ruben Dias",
    "player9": "Joao Félix",
    "player10": "Cristiano Ronaldo",
    "player11": "Bruno Fernandes"
  },
  {
    "title": "Chelsea v Bayer Leverkusen UCL 2011",
    "image": "https://media.gettyimages.com/id/124924069/photo/the-chelsea-starting-xi-against-bayer-le.jpg?s=1024x1024&w=gi&k=20&c=AeyAv65pH90u7Hky5a7o0f0uK2J8rNJh5HxV8FVb2qA=",
    "player1": "John Obi Mikel",
    "player2": "David Luiz",
    "player3": "Daniel Sturridge",
    "player4": "Petr Cech",
    "player5": "Branislav Ivanovic",
    "player6": "Fernando Torres",
    "player7": "Raul Meireles",
    "player8": "Juan Mata",
    "player9": "Florent Malouda",
    "player10": "Ashley Cole",
    "player11": "Jose Bosingwa"
  },
  { //
    "title": "Barcelona v Juventus UCL 2017",
    "image": "https://drive.google.com/uc?export=view&id=1vyzCMVMkaaTuEHrt9DR66O8Hxb9bsttr",
    "player1": "Ter stegen",
    "player2": "Umtiti",
    "player3": "Javier Mascherano",
    "player4": "ivan rakitic",
    "player5": "Jérémy Mathieu",
    "player6": "Pique",
    "player7": "Messi",
    "player8": "Sergio Roberto",
    "player9": "Neymar",
    "player10": "Iniesta",
    "player11": "Luis Suarez"
  },

  {
    "title": "Brazil vs Russia Friendly 2013",
    "image": "https://drive.google.com/uc?export=view&id=1uE41_wiAHbHlJXm1c81gkv2RmxG1rUHS",
    "player1": "Julio Cesar",
    "player2": "Hernanes",
    "player3": "Fred",
    "player4": "David Luiz",
    "player5": "Thiago Silva",
    "player6": "Oscar",
    "player7": "Daniel Alves",
    "player8": "Fernando Lucas",
    "player9": "Neymar",
    "player10": "Marcelo",
    "player11": "Kaka"
  },
  {
    "title": "England vs Netherlands Friendly 2016",
    "image": "https://media.gettyimages.com/id/518040106/photo/fbl-euro-2016-friendly-eng-ned.jpg?s=1024x1024&w=gi&k=20&c=U6aWSv0f537cnCKTkSsmnHrAZuyyWOgeM1dbLFQjpiw=",
    "player1": "Daniel Sturridge",
    "player2": "Ross Barkley",
    "player3": "Adam Lallana",
    "player4": "Chris Smalling",
    "player5": "Fraser Forster",
    "player6": "John Stones",
    "player7": "Kyle Walker",
    "player8": "Danny Rose",
    "player9": "Danny Drinkwater",
    "player10": "James Milner",
    "player11": "Jamie Vardy"
  },
  {
    "title": "Real Madrid v Tottenham Hotspur UCL 2013",
    "image": "https://drive.google.com/uc?export=view&id=1Y-XeL8GXU2VEVBZGE0ymzsXEfjQZHipE",
    "player1": "Iker Casillas",
    "player2": "Sergio Ramos",
    "player3": "Raul Albiol",
    "player4": "Xavi Alonso",
    "player5": "Sami Khedira",
    "player6": "Emmanuel Adebayor",
    "player7": "Cristiano Ronaldo",
    "player8": "Alvaro Arbeloa",
    "player9": "Marcelo",
    "player10": "Ricardo Carvalho",
    "player11": "Mesut Ozil"
  },
  {
    "title": "Italy World cup Winner Team 2006",
    "image": "https://drive.google.com/uc?export=view&id=1GoTNLRCI09uzkVyXrMFCj-5JDbp1oN3L",
    "player1": "Gianluigi Buffon",
    "player2": "Fabio Grosso",
    "player3": "Fabio Cannavaro",
    "player4": "Gianluca Zambrotta",
    "player5": "Marco Materazzi",
    "player6": "Gennaro Gattuso",
    "player7": "Francesco Totti",
    "player8": "Mauro Camoranesi",
    "player9": "Simone Perrotta",
    "player10": "Andrea Pirlo",
    "player11": "Luca Toni"
  },
  {
    "title": "Atletico 2019 vs Bayer 04 Leverkusen",
    "image": "https://drive.google.com/uc?export=view&id=1o2Cl7Wf6I20TaBsvI41u4RoHv7XUPtia",
    "player1":"Jan Oblak",
    "player2":"Josema Gimenez",
    "player3":"Felipe",
    "player4":"Thomas Partey",
    "player5":"Hector Herrera",
    "player6":"Renan Lodi",
    "player7":"Angel Correa",
    "player8":"Kieran Trippier",
    "player9":"Koke",
    "player10":"Saul Niguez",
    "player11":"Diego Costa",
  },
  {
    "title": "Serbia 2018 vs Brazil",
    "image": "https://drive.google.com/uc?export=view&id=1uLb6IX5RzYsVexhUioyKVZkptu4YzfK8",
    "player1":"V Stojkovic",
    "player2":"A Rukavina",
    "player3":"N Milenkovic",
    "player4":"M Veljkovic",
    "player5":"A Kolarov",
    "player6":"S Milinkovic-Savic",
    "player7":"N Matic",
    "player8":"D Tadic",
    "player9":"A Ljajic",
    "player10":"F Kostic",
    "player11":"A Mitrovic",
  },
  {
    "title": "Denmark 2023 vs slovenia",
    "image": "https://drive.google.com/uc?export=view&id=1E9hM4yF6wJhjb1RmBXpkS1snaQ8lNEHe",
    "player1":"Kasper Schmeichel",
    "player2":"Simon Kjaer",
    "player3":"Mathias Jorgensen",
    "player4":"Andreas Christensen",
    "player5":"Christian Eriksen",
    "player6":"Pierre-Emile Højbjerg",
    "player7":"Jens Stryger Larsen",
    "player8":"Alexander Bah",
    "player9":"Rasmus Højlund",
    "player10":"Jonas Wind",
    "player11":"Andreas Skov Olsen",
  },
  {
    "title": "Brazil 2002 ",
    "image": "https://drive.google.com/uc?export=view&id=1UYX6rBQsi843DC-xIfuPnzE22s4HX8u6",
    "player1":"Lúcio",
    "player2":"Edmílson",
    "player3":"Gilberto Silva",
    "player4":"Roque Júnior",
    "player5":"Ronaldinho",
    "player6":"Ronaldo",
    "player7":"Marcos",
    "player8":"Cafu",
    "player9":"Juninho",
    "player10":"Roberto Carlos",
    "player11":"Rivaldo",
  },
  {
    "title": "Real Madrid 2002 vs Bayer 04 Leverkusen",
    "image": "https://drive.google.com/uc?export=view&id=1uK3esnUeCjwlzt7tIWYJ5dRkluJ19xkw",
    "player1":"César",
    "player2":"Fernando Hierro",
    "player3":"Helguera",
    "player4":"Santiago Solari",
    "player5":"Luís Figo",
    "player6":"Zinedine Zidane",
    "player7":"Fernando Morientes",
    "player8":"Claude Makélélé",
    "player9":"Michel Salgado",
    "player10":"Raúl",
    "player11":"Roberto Carlos",
  },
  {
    "title": "Bayer 04 Leverkusen v Monaco Europa 2024",
    "image": "https://drive.google.com/uc?export=view&id=1I5RQh3ejN2Y2gNn7y_56TbG-kHRWlUAT",
    "player1": "Edmond Tapsoba",
    "player2": "Adam Hlozek",
    "player3": "Mitchel Bakker",
    "player4": "Jonathan Tah",
    "player5": "Robert Andrich",
    "player6": "Lukas Hradecky",
    "player7": "Exequiel Palacios",
    "player8": "Piero Hincapie",
    "player9": "Jeremie Frimpong",
    "player10": "Florian Wirtz",
    "player11": "Amine Adli"
  },
];


final List<Map<String, String>> Men_fe_elsora_data1 = [
  {"title": "Spurs 2016 vs Atletico Madrid",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.seattletimes.com%2Fsports%2Fsounders%2Fhow-the-starting-xi-photo-began-and-why-one-of-soccers-oldest-traditions-is-still-going-today%2F&psig=AOvVaw3O5kFXsyjxJHCxIY-llhur&ust=1722823040534000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPCW6Iue2ocDFQAAAAAdAAAAABAE",
    "player1":"Vorm",
    "player2":"Trippier",
    "player3":"Walkes",
    "player4":"Carter-Vickers",
    "player5":"Yedlin",
    "player6":"Wanyama",
    "player7":"Winks",
    "player8":"Lamela",
    "player9":"Eriksen",
    "player10":"Onomah",
    "player11":"Janssen",
  },
  {
    "title": "England vs Malta. World Cup Qualification 2016",
    "image": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.seattletimes.com%2Fsports%2Fsounders%2Fhow-the-starting-xi-photo-began-and-why-one-of-soccers-oldest-traditions-is-still-going-today%2F&psig=AOvVaw3O5kFXsyjxJHCxIY-llhur&ust=1722823040534000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPCW6Iue2ocDFQAAAAAdAAAAABAE",    "player1": "Joe Hart",
    "player2": "Kyle Walker",
    "player3": "Ryan Bertrand",
    "player4": "Jordan Henderson",
    "player5": "Gary Cahill",
    "player6": "John Stones",
    "player7": "Theo Walcott",
    "player8": "Dele Alli",
    "player9": "Daniel Sturridge",
    "player10": "Wayne Rooney (C)",
    "player11": "Jesse Lingard"
  },
  {
    "title": "Arsenal Invisibles",
    "image": "https://drive.google.com/uc?export=view&id=1PszP-GBoLRzXKMMI4Bz4o7AjZY72Z69U",
    "player1": "Viera",
    "player2": "Bergkamp",
    "player3": "Edu",
    "player4": "Gasper",
    "player5": "Lauren",
    "player6": "Campbell",
    "player7": "Toure",
    "player8": "Cole",
    "player9": "Lumberg",
    "player10": "Henry",
    "player11": "Pires"
  },

];