name: football
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  group_button: ^5.3.4
  flutter_speed_dial: ^7.0.0
  collection: ^1.16.0
  url_launcher: ^6.3.0
  share: ^2.0.4
  confetti: ^0.7.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  csv: ^6.0.0
  intl: ^0.19.0








dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1



flutter_icons:
  android: true
  ios: true
  image_path: "assets/main/icon.png"


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true







  assets:
    - assets/main/
    - assets/main/logos/
    - assets/main/games/
    - assets/30 challenge/
    - assets/saba7o/
    - assets/saba7o/men_fe_elsora/
    - assets/aqua ta7ady/
    - assets/acting_data.csv


  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri/Amiri-Regular.ttf
        - asset: fonts/Amiri/Amiri-Italic.ttf
          weight: 100
        - asset: fonts/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: fonts/Amiri/Amiri-BoldItalic.ttf
          weight: 700
    - family: Teko
      fonts:
        - asset: fonts/Teko/Teko-Regular.ttf
        - asset: fonts/Teko/Teko-Light.ttf
          weight: 100
        - asset: fonts/Teko/Teko-Bold.ttf
          weight: 700
        - asset: fonts/Teko/Teko-SemiBold.ttf
          weight: 700
        - asset: fonts/Teko/Teko-Medium.ttf
          weight: 700
    - family: Zain
      fonts:
        - asset: fonts/Zain/Zain-Regular.ttf
        - asset: fonts/Zain/Zain-Light.ttf
          weight: 100
        - asset: fonts/Zain/Zain-Bold.ttf
          weight: 700
        - asset: fonts/Zain/Zain-ExtraBold.ttf
          weight: 700
        - asset: fonts/Zain/Zain-ExtraLight.ttf
          weight: 700
        - asset: fonts/Zain/Zain-Black.ttf
          weight: 700
    - family: Sarpanch
      fonts:
        - asset: fonts/Sarpanch/Sarpanch-Regular.ttf
        - asset: fonts/Sarpanch/Sarpanch-Medium.ttf
          weight: 100
        - asset: fonts/Sarpanch/Sarpanch-Bold.ttf
          weight: 700
        - asset: fonts/Sarpanch/Sarpanch-ExtraBold.ttf
          weight: 700
        - asset: fonts/Sarpanch/Sarpanch-SemiBold.ttf
          weight: 700
        - asset: fonts/Sarpanch/Sarpanch-Black.ttf
          weight: 700
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron/Orbitron-Regular.ttf
        - asset: fonts/Orbitron/Orbitron-Medium.ttf
          weight: 100
        - asset: fonts/Orbitron/Orbitron-Bold.ttf
          weight: 700
        - asset: fonts/Orbitron/Orbitron-ExtraBold.ttf
          weight: 700
        - asset: fonts/Orbitron/Orbitron-SemiBold.ttf
          weight: 700
        - asset: fonts/Orbitron/Orbitron-Black.ttf
          weight: 700

