final List<Map<String, String>> Draw_data = [
  {"name": "1.FC Köln", "photo": "assets/main/logos/1.FC Köln.png"},
  {"name": "1.FC Union Berlin", "photo": "assets/main/logos/1.FC Union Berlin.png"},
  {"name": "1.FSV Mainz 05", "photo": "assets/main/logos/1.FSV Mainz 05.png"},
  {"name": "Aberdeen FC", "photo": "assets/main/logos/Aberdeen FC.png"},
  {"name": "AC Milan", "photo": "assets/main/logos/AC Milan.png"},
  {"name": "AC Monza", "photo": "assets/main/logos/AC Monza.png"},
  {"name": "AC Sparta Prague", "photo": "assets/main/logos/AC Sparta Prague.png"},
  {"name": "ACF Fiorentina", "photo": "assets/main/logos/ACF Fiorentina.png"},
  {"name": "AEK Athens", "photo": "assets/main/logos/AEK Athens.png"},
  {"name": "AFC Bournemouth", "photo": "assets/main/logos/AFC Bournemouth.png"},
  {"name": "Ajax Amsterdam", "photo": "assets/main/logos/Ajax Amsterdam.png"},
  {"name": "Al Ahly SC", "photo": "assets/main/logos/Al Ahly SC.png"},
  {"name": "AL-AHLI SAUDI F.C.", "photo": "assets/main/logos/AL-AHLI SAUDI F.C..png"},
  {"name": "AL-ETTIFAQ F.C.", "photo": "assets/main/logos/AL-ETTIFAQ F.C .png"},
  {"name": "AL-HILAL SAUDI F.C.", "photo": "assets/main/logos/AL-HILAL SAUDI F.C..png"},
  {"name": "AL-ITTIHAD JEDDAH F.C.", "photo": "assets/main/logos/AL-ITTIHAD JEDDAH F.C..png"},
  {"name": "Al-Masry SC", "photo": "assets/main/logos/Al-Masry SC.png"},
  {"name": "AL-NASSR F.C.", "photo": "assets/main/logos/AL-NASSR F.C..png"},
  {"name": "AL-SHABAB F.C.", "photo": "assets/main/logos/AL-SHABAB F.C..png"},
  {"name": "AL-WEHDA CLUB", "photo": "assets/main/logos/AL-WEHDA CLUB.png"},
  {"name": "Alanyaspor", "photo": "assets/main/logos/Alanyaspor.png"},
  {"name": "Alavés", "photo": "assets/main/logos/Alavés.png"},
  {"name": "Antalyaspor", "photo": "assets/main/logos/Antalyaspor.png"},
  {"name": "Arsenal FC", "photo": "assets/main/logos/Arsenal FC.png"},
  {"name": "AS Monaco", "photo": "assets/main/logos/AS Monaco.png"},
  {"name": "AS Roma", "photo": "assets/main/logos/AS Roma.png"},
  {"name": "AS Saint-Étienne", "photo": "assets/main/logos/AS Saint-Étienne.png"},
  {"name": "Aston Villa", "photo": "assets/main/logos/Aston Villa.png"},
  {"name": "Atalanta BC", "photo": "assets/main/logos/Atalanta BC.png"},
  {"name": "Athletic Bilbao", "photo": "assets/main/logos/Athletic Bilbao.png"},
  {"name": "Atlético de Madrid", "photo": "assets/main/logos/Atlético de Madrid.png"},
  {"name": "Austria Vienna", "photo": "assets/main/logos/Austria Vienna.png"},
  {"name": "AZ Alkmaar", "photo": "assets/main/logos/AZ Alkmaar.png"},
  {"name": "Basaksehir FK", "photo": "assets/main/logos/Basaksehir FK.png"},
  {"name": "Bayer 04 Leverkusen", "photo": "assets/main/logos/Bayer 04 Leverkusen.png"},
  {"name": "Bayern Munich", "photo": "assets/main/logos/Bayern Munich.png"},
  {"name": "Besiktas JK", "photo": "assets/main/logos/Besiktas JK.png"},
  {"name": "Boavista FC", "photo": "assets/main/logos/Boavista FC.png"},
  {"name": "Bologna FC 1909", "photo": "assets/main/logos/Bologna FC 1909.png"},
  {"name": "Borussia Dortmund", "photo": "assets/main/logos/Borussia Dortmund.png"},
  {"name": "Borussia Mönchengladbach", "photo": "assets/main/logos/Borussia Mönchengladbach.png"},
  {"name": "Brentford FC", "photo": "assets/main/logos/Brentford FC.png"},
  {"name": "Brighton & Hove Albion", "photo": "assets/main/logos/Brighton & Hove Albion.png"},
  {"name": "BSC Young Boys", "photo": "assets/main/logos/BSC Young Boys.png"},
  {"name": "Burnley FC", "photo": "assets/main/logos/Burnley FC.png"},
  {"name": "CA Osasuna", "photo": "assets/main/logos/CA Osasuna.png"},
  {"name": "Cagliari Calcio", "photo": "assets/main/logos/Cagliari Calcio.png"},
  {"name": "Celta de Vigo", "photo": "assets/main/logos/Celta de Vigo.png"},
  {"name": "Celtic FC", "photo": "assets/main/logos/Celtic FC.png"},
  {"name": "Chelsea FC", "photo": "assets/main/logos/Chelsea FC.png"},
  {"name": "Club Brugge KV", "photo": "assets/main/logos/Club Brugge KV.png"},
  {"name": "Crystal Palace", "photo": "assets/main/logos/Crystal Palace.png"},
  {"name": "CSKA Moscow", "photo": "assets/main/logos/CSKA Moscow.png"},
  {"name": "Cádiz CF", "photo": "assets/main/logos/Cádiz CF.png"},
  {"name": "Deportivo Alavés", "photo": "assets/main/logos/Deportivo Alavés.png"},
  {"name": "Dynamo Kyiv", "photo": "assets/main/logos/Dynamo Kyiv.png"},
  {"name": "Dynamo Moscow", "photo": "assets/main/logos/Dynamo Moscow.png"},
  {"name": "Eintracht Frankfurt", "photo": "assets/main/logos/Eintracht Frankfurt.png"},
  {"name": "El Dakhleya", "photo": "assets/main/logos/El Dakhleya .png"},
  {"name": "ENPPI", "photo": "assets/main/logos/ENPPI.png"},
  {"name": "Everton FC", "photo": "assets/main/logos/Everton FC.png"},
  {"name": "Excelsior Rotterdam", "photo": "assets/main/logos/Excelsior Rotterdam.png"},
  {"name": "FC Barcelona", "photo": "assets/main/logos/FC Barcelona.png"},
  {"name": "FC Basel 1893", "photo": "assets/main/logos/FC Basel 1893.png"},
  {"name": "FC Copenhagen", "photo": "assets/main/logos/FC Copenhagen.png"},
  {"name": "FC Empoli", "photo": "assets/main/logos/FC Empoli.png"},
  {"name": "FC Metz", "photo": "assets/main/logos/FC Metz.png"},
  {"name": "FC Midtjylland", "photo": "assets/main/logos/FC Midtjylland.png"},
  {"name": "FC Nantes", "photo": "assets/main/logos/FC Nantes.png"},
  {"name": "FC Porto", "photo": "assets/main/logos/FC Porto.png"},
  {"name": "FC Toulouse", "photo": "assets/main/logos/FC Toulouse.png"},
  {"name": "FC Utrecht", "photo": "assets/main/logos/FC Utrecht.png"},
  {"name": "FC Viktoria Plzen", "photo": "assets/main/logos/FC Viktoria Plzen.png"},
  {"name": "Fenerbahce", "photo": "assets/main/logos/Fenerbahce.png"},
  {"name": "Feyenoord Rotterdam", "photo": "assets/main/logos/Feyenoord Rotterdam.png"},
  {"name": "FK Krasnodar", "photo": "assets/main/logos/FK Krasnodar.png"},
  {"name": "Fulham FC", "photo": "assets/main/logos/Fulham FC.png"},
  {"name": "G. Bordeaux", "photo": "assets/main/logos/G. Bordeaux.png"},
  {"name": "Galatasaray", "photo": "assets/main/logos/Galatasaray.png"},
  {"name": "Genoa CFC", "photo": "assets/main/logos/Genoa CFC.png"},
  {"name": "Getafe CF", "photo": "assets/main/logos/Getafe CF.png"},
  {"name": "Girona FC", "photo": "assets/main/logos/Girona FC.png"},
  {"name": "GNK Dinamo Zagreb", "photo": "assets/main/logos/GNK Dinamo Zagreb.png"},
  {"name": "Granada CF", "photo": "assets/main/logos/Granada CF.png"},
  {"name": "Heart of Midlothian FC", "photo": "assets/main/logos/Heart of Midlothian FC.png"},
  {"name": "Hellas Verona", "photo": "assets/main/logos/Hellas Verona.png"},
  {"name": "Hertha BSC", "photo": "assets/main/logos/Hertha BSC.png"},
  {"name": "Inter Milan", "photo": "assets/main/logos/Inter Milan.png"},
  {"name": "Ittihad Alexandria Club", "photo": "assets/main/logos/Ittihad Alexandria Club.png"},
  {"name": "Juventus FC", "photo": "assets/main/logos/Juventus FC.png"},
  {"name": "KAA Gent", "photo": "assets/main/logos/KAA Gent.png"},
  {"name": "KRC Genk", "photo": "assets/main/logos/KRC Genk.png"},
  {"name": "LASK", "photo": "assets/main/logos/LASK.png"},
  {"name": "Leeds United", "photo": "assets/main/logos/Leeds United.png"},
  {"name": "Legia Warszawa", "photo": "assets/main/logos/Legia Warszawa.png"},
  {"name": "Leicester City", "photo": "assets/main/logos/Leicester City.png"},
  {"name": "Levante UD", "photo": "assets/main/logos/Levante UD.png"},
  {"name": "Liverpool FC", "photo": "assets/main/logos/Liverpool FC.png"},
  {"name": "Lokomotiv Moscow", "photo": "assets/main/logos/Lokomotiv Moscow.png"},
  {"name": "LOSC Lille", "photo": "assets/main/logos/LOSC Lille.png"},
  {"name": "Luton Town", "photo": "assets/main/logos/Luton Town.png"},
  {"name": "Manchester City", "photo": "assets/main/logos/Manchester City.png"},
  {"name": "Manchester United", "photo": "assets/main/logos/Manchester United.png"},
  {"name": "Montpellier HSC", "photo": "assets/main/logos/Montpellier HSC.png"},
  {"name": "NEC Nijmegen", "photo": "assets/main/logos/NEC Nijmegen.png"},
  {"name": "Newcastle United", "photo": "assets/main/logos/Newcastle United.png"},
  {"name": "Norwich", "photo": "assets/main/logos/Norwich.png"},
  {"name": "Nottingham Forest", "photo": "assets/main/logos/Nottingham Forest.png"},
  {"name": "OGC Nice", "photo": "assets/main/logos/OGC Nice.png"},
  {"name": "Olympiacos Piraeus", "photo": "assets/main/logos/Olympiacos Piraeus.png"},
  {"name": "Olympique Lyon", "photo": "assets/main/logos/Olympique Lyon.png"},
  {"name": "Olympique Marseille", "photo": "assets/main/logos/Olympique Marseille.png"},
  {"name": "Panathinaikos Athens", "photo": "assets/main/logos/Panathinaikos Athens.png"},
  {"name": "PAOK Thessaloniki", "photo": "assets/main/logos/PAOK Thessaloniki.png"},
  {"name": "Paris Saint-Germain", "photo": "assets/main/logos/Paris Saint-Germain.png"},
  {"name": "Petrojet FC", "photo": "assets/main/logos/Petrojet FC.png"},
  {"name": "Portimonense SC", "photo": "assets/main/logos/Portimonense SC.png"},
  {"name": "PSV Eindhoven", "photo": "assets/main/logos/PSV Eindhoven.png"},
  {"name": "Rangers FC", "photo": "assets/main/logos/Rangers FC.png"},
  {"name": "Rayo Vallecano", "photo": "assets/main/logos/Rayo Vallecano.png"},
  {"name": "RB Leipzig", "photo": "assets/main/logos/RB Leipzig.png"},
  {"name": "RC Lens", "photo": "assets/main/logos/RC Lens.png"},
  {"name": "RCD Mallorca", "photo": "assets/main/logos/RCD Mallorca.png"},
  {"name": "Real Betis Balompié", "photo": "assets/main/logos/Real Betis Balompié.png"},
  {"name": "Real Madrid", "photo": "assets/main/logos/Real Madrid.png"},
  {"name": "Real Sociedad", "photo": "assets/main/logos/Real Sociedad.png"},
  {"name": "Real Valladolid CF", "photo": "assets/main/logos/Real Valladolid CF.png"},
  {"name": "Red Bull Salzburg", "photo": "assets/main/logos/Red Bull Salzburg.png"},
  {"name": "Red Star Belgrade", "photo": "assets/main/logos/Red Star Belgrade.png"},
  {"name": "Rio Ave FC", "photo": "assets/main/logos/Rio Ave FC.png"},
  {"name": "Royal Antwerp FC", "photo": "assets/main/logos/Royal Antwerp FC.png"},
  {"name": "Royale Union Saint Gilloise", "photo": "assets/main/logos/Royale Union Saint Gilloise.png"},
  {"name": "RSC Anderlecht", "photo": "assets/main/logos/RSC Anderlecht.png"},
  {"name": "SC Braga", "photo": "assets/main/logos/SC Braga.png"},
  {"name": "SC Freiburg", "photo": "assets/main/logos/SC Freiburg.png"},
  {"name": "SC Heerenveen", "photo": "assets/main/logos/SC Heerenveen.png"},
  {"name": "Sevilla FC", "photo": "assets/main/logos/Sevilla FC.png"},
  {"name": "Shakhtar Donetsk", "photo": "assets/main/logos/Shakhtar Donetsk.png"},
  {"name": "Sheffield United", "photo": "assets/main/logos/Sheffield United.png"},
  {"name": "SK Slavia Prague", "photo": "assets/main/logos/SK Slavia Prague.png"},
  {"name": "SL Benfica", "photo": "assets/main/logos/SL Benfica.png"},
  {"name": "Southampton FC", "photo": "assets/main/logos/Southampton FC.png"},
  {"name": "Sparta Rotterdam", "photo": "assets/main/logos/Sparta Rotterdam.png"},
  {"name": "Sporting CP", "photo": "assets/main/logos/Sporting CP.png"},
  {"name": "SS Lazio", "photo": "assets/main/logos/SS Lazio.png"},
  {"name": "SSC Napoli", "photo": "assets/main/logos/SSC Napoli.png"},
  {"name": "Stade Reims", "photo": "assets/main/logos/Stade Reims.png"},
  {"name": "Stade Rennais FC", "photo": "assets/main/logos/Stade Rennais FC.png"},
  {"name": "SV Darmstadt 98", "photo": "assets/main/logos/SV Darmstadt 98.png"},
  {"name": "SV Werder Bremen", "photo": "assets/main/logos/SV Werder Bremen.png"},
  {"name": "Torino FC", "photo": "assets/main/logos/Torino FC.png"},
  {"name": "Tottenham Hotspur", "photo": "assets/main/logos/Tottenham Hotspur.png"},
  {"name": "Trabzonspor", "photo": "assets/main/logos/Trabzonspor.png"},
  {"name": "TSG 1899 Hoffenheim", "photo": "assets/main/logos/TSG 1899 Hoffenheim.png"},
  {"name": "Twente Enschede FC", "photo": "assets/main/logos/Twente Enschede FC.png"},
  {"name": "UD Almería", "photo": "assets/main/logos/UD Almería.png"},
  {"name": "UD Las Palmas", "photo": "assets/main/logos/UD Las Palmas.png"},
  {"name": "Udinese Calcio", "photo": "assets/main/logos/Udinese Calcio.png"},
  {"name": "US Salernitana 1919", "photo": "assets/main/logos/US Salernitana 1919.png"},
  {"name": "US Sassuolo", "photo": "assets/main/logos/US Sassuolo.png"},
  {"name": "Valencia CF", "photo": "assets/main/logos/Valencia CF.png"},
  {"name": "VfB Stuttgart", "photo": "assets/main/logos/VfB Stuttgart.png"},
  {"name": "VfL Bochum", "photo": "assets/main/logos/VfL Bochum.png"},
  {"name": "VfL Wolfsburg", "photo": "assets/main/logos/VfL Wolfsburg.png"},
  {"name": "Villarreal CF", "photo": "assets/main/logos/Villarreal CF.png"},
  {"name": "Vitória Guimarães SC", "photo": "assets/main/logos/Vitória Guimarães SC.png"},
  {"name": "West Ham United", "photo": "assets/main/logos/West Ham United.png"},
  {"name": "Wolverhampton Wanderers", "photo": "assets/main/logos/Wolverhampton Wanderers.png"},
  {"name": "Zamalek SC", "photo": "assets/main/logos/Zamalek SC.png"},
  {"name": "Zenit St. Petersburg", "photo": "assets/main/logos/Zenit St. Petersburg.png"},
];
