final List<Map<String, String>> Men_fe_elsora_data = [
  {"title": "Spurs 2016 vs Atletico Madrid",
    "image": "assets/saba7o/men_fe_elsora/spurs2016.jpg",
    "player1":"Vorm",
    "player2":"Trippier",
    "player3":"Walkes",
    "player4":"Carter-Vickers",
    "player5":"Yedlin",
    "player6":"Wanyama",
    "player7":"Winks",
    "player8":"Lamela",
    "player9":"Eriksen",
    "player10":"Onomah",
    "player11":"Janssen",
  },
  {
    "title": "Atletico 2019 vs Bayer 04 Leverkusen",
    "image": "assets/saba7o/men_fe_elsora/atletico2019.jpg",
    "player1":"Jan Oblak",
    "player2":"Josema Gimenez",
    "player3":"Felipe",
    "player4":"Thomas Partey",
    "player5":"Hector Herrera",
    "player6":"Renan Lodi",
    "player7":"Angel Correa",
    "player8":"Kieran Trippier",
    "player9":"Koke",
    "player10":"Saul Niguez",
    "player11":"Diego Costa",
  },
  {
    "title": "Serbia 2018 vs Brazil",
    "image": "assets/saba7o/men_fe_elsora/serbia2018.jpg",
    "player1":"V Stojkovic",
    "player2":"A Rukavina",
    "player3":"N Milenkovic",
    "player4":"M Veljkovic",
    "player5":"A Kolarov",
    "player6":"S Milinkovic-Savic",
    "player7":"N Matic",
    "player8":"D Tadic",
    "player9":"A Ljajic",
    "player10":"F Kostic",
    "player11":"A Mitrovic",
  },
  {
    "title": "Denmark 2023 vs slovenia",
    "image": "assets/saba7o/men_fe_elsora/denmark2023.jpg",
    "player1":"Kasper Schmeichel",
    "player2":"Simon Kjaer",
    "player3":"Mathias Jorgensen",
    "player4":"Andreas Christensen",
    "player5":"Christian Eriksen",
    "player6":"Pierre-Emile Højbjerg",
    "player7":"Jens Stryger Larsen",
    "player8":"Alexander Bah",
    "player9":"Rasmus Højlund",
    "player10":"Jonas Wind",
    "player11":"Andreas Skov Olsen",
  },
  {
    "title": "Brazil 2002 ",
    "image": "assets/saba7o/men_fe_elsora/brazil2002.jpg",
    "player1":"Lúcio",
    "player2":"Edmílson",
    "player3":"Gilberto Silva",
    "player4":"Roque Júnior",
    "player5":"Ronaldinho",
    "player6":"Ronaldo",
    "player7":"Marcos",
    "player8":"Cafu",
    "player9":"Juninho",
    "player10":"Roberto Carlos",
    "player11":"Rivaldo",
  },
  {
    "title": "Real Madrid 2002 vs Bayer 04 Leverkusen",
    "image": "assets/saba7o/men_fe_elsora/realMadrid2002.png",
    "player1":"César",
    "player2":"Fernando Hierro",
    "player3":"Helguera",
    "player4":"Santiago Solari",
    "player5":"Luís Figo",
    "player6":"Zinedine Zidane",
    "player7":"Fernando Morientes",
    "player8":"Claude Makélélé",
    "player9":"Michel Salgado",
    "player10":"Raúl",
    "player11":"Roberto Carlos",
  },
];