final List<Map<String, String>> Whisper_data = [
  {"name": "Juventus", "photo": ""},
  {"name": "Gareth Bale", "photo": ""},
  {"name": "Manchester United", "photo": ""},
  {"name": "Erling Haaland", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
  {"name": "Barcelona", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Paul Pogba", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Harry Kane", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sergio Agüero", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Cody Gakpo", "photo": ""},
  {"name": "N'Golo Kanté", "photo": ""},
  {"name": "Toni Kroos", "photo": ""},
  {"name": "Manuel Neuer", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Chelsea", "photo": ""},
  {"name": "Marco Reus", "photo": ""},
  {"name": "Edouard Mendy", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Christian Pulisic", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Bayern Munich", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "Thomas Müller", "photo": ""},
  {"name": "Real Madrid", "photo": ""},
  {"name": "AC Milan", "photo": ""},
  {"name": "Man City", "photo": ""},
  {"name": "Virgil van Dijk", "photo": ""},
  {"name": "Inter Milan", "photo": ""},
  {"name": "Mohamed Salah", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "Lacazette", "photo": ""},
  {"name": "Gakpo", "photo": ""},
  {"name": "Arsenal", "photo": ""},
  {"name": "Liverpool", "photo": ""},
  {"name": "Muller", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Man United", "photo": ""},
  {"name": "Yannick Carrasco", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Jude Bellingham", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
];
