final List<Map<String, String>> Whisper_data = [
  {"name": "Gareth Bale", "photo": ""},
  {"name": "Erling Haaland", "photo": ""},
  {"name": "Cristiano Ronaldo", "photo": ""},
  {"name": "Neymar", "photo": ""},
  {"name": "Kylian Mbappé", "photo": ""},
  {"name": "David Alaba", "photo": ""},
  {"name": "Paul Pogba", "photo": ""},
  {"name": "Frenkie de Jong", "photo": ""},
  {"name": "Sadio Mané", "photo": ""},
  {"name": "Lionel Messi", "photo": ""},
  {"name": "Harry Kane", "photo": ""},
  {"name": "Sergio Agüero", "photo": ""},
  {"name": "João Félix", "photo": ""},
  {"name": "Cody Gakpo", "photo": ""},
  {"name": "N'Golo Kanté", "photo": ""},
  {"name": "Toni Kroos", "photo": ""},
  {"name": "Manuel Neuer", "photo": ""},
  {"name": "Houssem Aouar", "photo": ""},
  {"name": "Marco Reus", "photo": ""},
  {"name": "Edouard Mendy", "photo": ""},
  {"name": "Christian Pulisic", "photo": ""},
  {"name": "Mason Mount", "photo": ""},
  {"name": "Luka Modrić", "photo": ""},
  {"name": "Thomas Müller", "photo": ""},
  {"name": "Virgil van Dijk", "photo": ""},
  {"name": "Mohamed Salah", "photo": ""},
  {"name": "Yannick Carrasco", "photo": ""},
  {"name": "Jude Bellingham", "photo": ""},
  {"name": "Kevin De Bruyne", "photo": ""},
  {"name": "Antoine Griezmann", "photo": ""},
  {"name": "Luis Suárez", "photo": ""},
  {"name": "Jan Oblak", "photo": ""},
  {"name": "Sergio Ramos", "photo": ""},
  {"name": "Eden Hazard", "photo": ""},
  {"name": "Thiago Alcântara", "photo": ""},
  {"name": "Trent Alexander-Arnold", "photo": ""},
  {"name": "Robert Lewandowski", "photo": ""},
  {"name": "Alisson Becker", "photo": ""},
  {"name": "Andrew Robertson", "photo": ""},
  {"name": "Raheem Sterling", "photo": ""},
  {"name": "Karim Benzema", "photo": ""},
  {"name": "Son Heung-min", "photo": ""},
  {"name": "Joshua Kimmich", "photo": ""},
  {"name": "Kai Havertz", "photo": ""},
  {"name": "Romelu Lukaku", "photo": ""},
  {"name": "Phil Foden", "photo": ""},
  {"name": "Lautaro Martínez", "photo": ""},
  {"name": "Achraf Hakimi", "photo": ""},
  {"name": "Jack Grealish", "photo": ""},
  {"name": "Ansu Fati", "photo": ""},
  {"name": "Gianluigi Donnarumma", "photo": ""},
  {"name": "Rodri", "photo": ""},
  {"name": "Bruno Fernandes", "photo": ""},
  {"name": "Marcos Llorente", "photo": ""},
  {"name": "Matthijs de Ligt", "photo": ""},
  {"name": "Memphis Depay", "photo": ""},
  {"name": "Declan Rice", "photo": ""},
  {"name": "Bukayo Saka", "photo": ""},
  {"name": "Marcelo Brozović", "photo": ""},
  {"name": "Leon Goretzka", "photo": ""},
  {"name": "Kingsley Coman", "photo": ""},
  {"name": "Gerard Moreno", "photo": ""},
  {"name": "Federico Chiesa", "photo": ""},
  {"name": "Marquinhos", "photo": ""},
  {"name": "Wissam Ben Yedder", "photo": ""},
  {"name": "Saúl Ñíguez", "photo": ""},
  {"name": "Raphaël Varane", "photo": ""},
  {"name": "Mikel Oyarzabal", "photo": ""},
  {"name": "Leroy Sané", "photo": ""},
  {"name": "Dani Carvajal", "photo": ""},
  {"name": "Ciro Immobile", "photo": ""},
  {"name": "Bernardo Silva", "photo": ""},
  {"name": "Aymeric Laporte", "photo": ""},
  {"name": "João Cancelo", "photo": ""},
  {"name": "Roberto Firmino", "photo": ""},
  {"name": "Jordan Henderson", "photo": ""},
  {"name": "Niklas Süle", "photo": ""},
  {"name": "Miralem Pjanić", "photo": ""},
  {"name": "Kalidou Koulibaly", "photo": ""},
  {"name": "Dele Alli", "photo": ""},
  {"name": "Hakim Ziyech", "photo": ""},
  {"name": "Alex Sandro", "photo": ""},
  {"name": "Pierre-Emerick Aubameyang", "photo": ""},
  {"name": "Mauro Icardi", "photo": ""},
  {"name": "Rodrigo de Paul", "photo": ""},
  {"name": "Raúl Jiménez", "photo": ""},
  {"name": "Riyad Mahrez", "photo": ""},
  {"name": "Nicolas Pépé", "photo": ""},
  {"name": "Serge Gnabry", "photo": ""},
  {"name": "Timo Werner", "photo": ""},
  {"name": "Eduardo Camavinga", "photo": ""},
  {"name": "Milan Škriniar", "photo": ""},
  {"name": "Christian Eriksen", "photo": ""},
  {"name": "James Maddison", "photo": ""},
  {"name": "Thiago Silva", "photo": ""},
  {"name": "Stefan de Vrij", "photo": ""},
  {"name": "Sergej Milinković-Savić", "photo": ""},
  {"name": "Martin Ødegaard", "photo": ""},
  {"name": "Kostas Manolas", "photo": ""},
  {"name": "Lucas Digne", "photo": ""},
  {"name": "João Moutinho", "photo": ""},
  {"name": "André Silva", "photo": ""},
  {"name": "David Silva", "photo": ""},
  {"name": "Koke", "photo": ""},
  {"name": "Rafael Leão", "photo": ""},
  {"name": "Diogo Jota", "photo": ""},
  {"name": "Ben Chilwell", "photo": ""},
  {"name": "Fabián Ruiz", "photo": ""},
  {"name": "Danny Ings", "photo": ""},
  {"name": "Emiliano Martínez", "photo": ""},
  {"name": "Rodrigo", "photo": ""},
  {"name": "Lucas Paquetá", "photo": ""},
  {"name": "Wilfred Ndidi", "photo": ""},
  {"name": "Jorginho", "photo": ""},
  {"name": "Mason Greenwood", "photo": ""},
  {"name": "Pedri", "photo": ""},
  {"name": "Eduardo Salvio", "photo": ""},
  {"name": "Nikola Vlašić", "photo": ""},
  {"name": "Patrik Schick", "photo": ""},
  {"name": "Alejandro Gómez", "photo": ""},
  {"name": "Alexander Isak", "photo": ""},
  {"name": "Zizo", "photo": ""},
  {"name": "Renato Sanches", "photo": ""},
  {"name": "Ezri Konsa", "photo": ""},
  {"name": "João Pedro", "photo": ""},
  {"name": "Conor Gallagher", "photo": ""},
  {"name": "Tammy Abraham", "photo": ""},
  {"name": "Allan Saint-Maximin", "photo": ""},
  {"name": "Ivan Perišić", "photo": ""},
  {"name": "Aaron Ramsey", "photo": ""},
  {"name": "Kaka", "photo": ""},
  {"name": "Donny van de Beek", "photo": ""},
  {"name": "Alphonso Davies", "photo": ""},
  {"name": "Lucas Hernández", "photo": ""},
  {"name": "Georginio Wijnaldum", "photo": ""},
  {"name": "Jordan Pickford", "photo": ""},
  {"name": "Youri Tielemans", "photo": ""},
  {"name": "Kieran Trippier", "photo": ""},
  {"name": "Mats Hummels", "photo": ""},
  {"name": "Hirving Lozano", "photo": ""},
  {"name": "Youssef En-Nesyri", "photo": ""},
  {"name": "Vinícius Júnior", "photo": ""},
  {"name": "Richarlison", "photo": ""},
  {"name": "Casemiro", "photo": ""},
  {"name": "Rúben Dias", "photo": ""},
  {"name": "Eric García", "photo": ""},
];
